Repository 1024pix/pix-ui, pull requests merged in 2020-11, with the labels that each got.

#40 [TECH] Afficher l'erreur levée par un bouton.
  .gitignore
  addon/components/pix-button.js
Labels: Tech review OK, cross-team, team-evaluation

#39 [DesignFix] Corriger le design de la PixReturnTo
  addon/styles/_pix-return-to.scss
Labels: cross-team

#41 [FEATURE] Ajout du composant pix-select
  addon/components/pix-select.hbs
  addon/stories/pix-select.stories.js
  addon/styles/_pix-select.scss
  addon/styles/addon.scss
  app/components/pix-select.js
  package-lock.json
  package.json
  tests/integration/components/pix-select-test.js
Labels: Tech review Needed, cross-team, team-prescription

#42 [DOC] Mise à jour de la documentation pour faire un déploiement de Pix-UI
  docs/make-a-release.md
Labels: Tech review Needed, cross-team

#43 [TECH] Ne pas lancer circle-ci sur la branche gh-pages
  .circleci/config.yml
Labels: Tech review Needed, cross-team
