Repository 1024pix/pix-ui, pull requests merged in 2020-10, with the labels that each got.

#35 [FEATURE] Ajout du composant Bouton.
  addon/components/pix-button.hbs
  addon/components/pix-button.js
  addon/stories/pix-button.stories.js
  addon/styles/_pix-button.scss
  addon/styles/addon.scss
  app/components/pix-button.js
  tests/integration/components/pix-button-test.js
Labels: Tech review Needed, cross-team, team-evaluation

#36 [FEATURE] Ajout du composant PixStars (pix-1448)
  addon/components/pix-stars.hbs
  addon/components/pix-stars.js
  addon/stories/pix-stars.stories.js
  addon/styles/_pix-stars.scss
  addon/styles/addon.scss
  app/components/pix-stars.js
  package-lock.json
  package.json
  tests/integration/components/pix-stars-test.js
Labels: Func Review OK, Tech review OK, team-evaluation, team-prescription

#37 [STYLE] Les étoiles bleues "vides" de PixStars ne doivent pas avoir de bordure
  addon/styles/_pix-stars.scss
Labels: Tech review Needed, team-prescription
