Repository 1024pix/pix-ui, pull requests merged in 2020-12, with the labels that each got.

#44 [TECH] Skip la CI sur les gh-pages
  package.json
Labels: Tech review Needed, cross-team

#45 [FEATURE] Création du composant de bannière de filtres (PIX-1675).
  README.md
  addon/components/pix-filter-banner.hbs
  addon/components/pix-filter-banner.js
  addon/stories/pix-filter-banner.stories.js
  addon/styles/_pix-filter-banner.scss
  addon/styles/addon.scss
  app/components/pix-filter-banner.js
  tests/integration/components/pix-filter-banner-test.js
Labels: :rocket: Ready to Merge, Design review OK, Tech review OK, team-certif, team-prescription

#46 [FEATURE] Création du composant multi-select (PIX-1674).
  addon/components/pix-multi-select.hbs
  addon/components/pix-multi-select.js
  addon/stories/pix-multi-select.stories.js
  addon/stories/pix-select.stories.js
  addon/styles/_pix-multi-select.scss
  addon/styles/addon.scss
  app/components/pix-multi-select.js
  package-lock.json
  package.json
  tests/integration/components/pix-multi-select-test.js
Labels: :rocket: Ready to Merge, Design review OK, Tech review Needed, Tech review OK, team-certif, team-prescription

#51 [TECH] Ne pas utiliser de mot clé ember comme nom de paramètre
  addon/components/pix-button.js
  addon/stories/pix-button.stories.js
  tests/integration/components/pix-button-test.js
Labels: cross-team

#47 [TECH] Corriger les erreurs eslint
  .eslintrc.js
  .npmignore
  addon/components/pix-button.hbs
  addon/stories/pix-button.stories.js
  blueprints/pix-component/index.js
  blueprints/pix-component/utilities/insert-into-file.js
  package-lock.json
  package.json
  scripts/get-pull-requests-to-release-in-prod.js
Labels: Tech review Needed, cross-team

#49 [TECH] Ajouter le linter aux build circle-ci
  .circleci/config.yml
Labels: :warning: PR Inheritance, Tech review Needed, cross-team

#50 [TECH] Mise à jour des dépendances pix-ui
  .storybook/main.js
  .storybook/preview.js
  addon/components/pix-message.hbs
  addon/components/pix-message.js
  addon/components/pix-tooltip.hbs
  addon/components/pix-tooltip.js
  blueprints/pix-component/index.js
  package-lock.json
  package.json
Labels: :warning: PR Inheritance, Tech review Needed, cross-team

#52 [TECH] Organisation des composants en categories
  addon/components/pix-multi-select.js
  addon/stories/pix-action-button.stories.js
  addon/stories/pix-background-header.stories.js
  addon/stories/pix-banner.stories.js
  addon/stories/pix-button.stories.js
  addon/stories/pix-filter-banner.stories.js
  addon/stories/pix-message.stories.js
  addon/stories/pix-multi-select.stories.js
  addon/stories/pix-return-to.stories.js
  addon/stories/pix-stars.stories.js
  addon/stories/pix-tag.stories.js
  addon/stories/pix-tooltip.stories.js
  package-lock.json
  package.json
Labels: :warning: PR Inheritance, Tech review OK, cross-team

#53 [TECH] Ajouter knobs au projet
  .storybook/main.js
  addon/stories/pix-stars.stories.js
  package-lock.json
  package.json
Labels: :warning: PR Inheritance, Tech review Needed, cross-team

#54 [TECH] Envoyer un message d'erreur plus explicite pour le PixButton
  addon/components/pix-button.js
  addon/stories/pix-button.stories.js
Labels: Tech review Needed, cross-team

#56 [FEATURE] Ajout des variantes jaunes et grises pour le composant PixTag
  addon/stories/pix-tag.stories.js
  addon/styles/_pix-tag.scss
Labels: Design Review Needed, Tech review Needed, cross-team

#48 [FEATURE] Donner la possibilité de faire une recherche sur un multi-select (Pix-1677)
  addon/components/pix-multi-select.hbs
  addon/components/pix-multi-select.js
  addon/stories/pix-multi-select.stories.js
  addon/styles/_pix-multi-select.scss
  tests/integration/components/pix-multi-select-test.js
Labels: :rocket: Ready to Merge, Design review OK, Func Review OK, Tech review OK, cross-team

#57 [Feature] Ajout de l'argument uppercase sur le composant PixTag
  addon/components/pix-tag.hbs
  addon/stories/pix-tag.stories.js
  addon/styles/_pix-tag.scss
  tests/integration/components/pix-tag-test.js
Labels: Tech review Needed, cross-team

#58 [TECH] Donner un id fixe directement au mutliselect cherchable
  addon/components/pix-multi-select.hbs
  addon/stories/pix-multi-select.stories.js
Labels: cross-team

#55 [FEATURE] Modification des addons dépréciés
  .storybook/main.js
  .storybook/preview.js
  addon/stories/pix-stars.stories.js
  addon/stories/pix-stars.stories.mdx
  blueprints/pix-component/files/addon/stories/pix-__name__.stories.js
  blueprints/pix-component/files/addon/stories/pix-__name__.stories.mdx
  package-lock.json
  package.json
Labels: Tech review Needed, cross-team

#59 [FEATURE] Ajout du PixTag compact
  addon/components/pix-tag.hbs
  addon/components/pix-tag.js
  addon/stories/pix-tag.stories.js
  addon/styles/_colors.scss
  addon/styles/_pix-tag.scss
  package.json
  tests/integration/components/pix-tag-test.js
Labels: cross-team
