Repository 1024pix/pix-ui, pull requests merged in 2020-07, with the labels that each got.

#22 [FEATURE] Ajout d'un PixBackgroundBlue & PixBlocShadow
  .storybook/preview.js
  addon/components/pix-background-header.hbs
  addon/components/pix-background-header.js
  addon/components/pix-block.hbs
  addon/components/pix-block.js
  addon/stories/pix-background-header.stories.js
  addon/stories/pix-block.stories.js
  addon/stories/pix-message.stories.js
  addon/stories/pix-tag.stories.js
  addon/stories/pix-tooltip.stories.js
  addon/styles/_breakpoints.scss
  addon/styles/_colors.scss
  addon/styles/_pix-background-header.scss
  addon/styles/_pix-block.scss
  addon/styles/addon.scss
  app/components/pix-background-header.js
  app/components/pix-block.js
  tests/integration/components/pix-background-header-test.js
  tests/integration/components/pix-block-test.js
Labels: Tech review Needed, team-certif, team-evaluation

#19 [TECH] Ajout du addon-a11y pour vérifier des points d'accessibilité sur les add-on pix.
  .storybook/main.js
  .storybook/preview.js
  package-lock.json
  package.json
Labels: team-evaluation

#26 [TECH] Changer le port de l'app Ember Pix UI
  .ember-cli
Labels: Tech review Needed, team-acces, team-certif, team-evaluation, team-prescription

#25 [FEATURE] Ajout du composant PixLinkBack
  .storybook/preview-head.html
  addon/components/pix-link-back.hbs
  addon/components/pix-link-back.js
  addon/stories/pix-background-header.stories.js
  addon/stories/pix-link-back.stories.js
  addon/styles/_pix-link-back.scss
  addon/styles/addon.scss
  app/components/pix-link-back.js
  package-lock.json
  package.json
  tests/helpers/create-glimmer-component.js
  tests/integration/components/pix-link-back-test.js
  tests/unit/components/pix-link-back-test.js
Labels: Design Review Needed, Tech review Needed

#27 [BUGFIX] Corrections de la PixLinkBack renommée en PixReturnTo
  addon/components/pix-link-back.hbs
  addon/components/pix-return-to.hbs
  addon/components/pix-return-to.js
  addon/stories/pix-link-back.stories.js
  addon/styles/_pix-return-to.scss
  addon/styles/addon.scss
  app/components/pix-link-back.js
  app/components/pix-return-to.js
  tests/integration/components/pix-link-back-test.js
  tests/integration/components/pix-return-to-test.js
  tests/unit/components/pix-return-to-test.js
Labels: Tech review Needed, team-certif, team-evaluation

#23 [TECH] Ajout d'un reset CSS
  addon/styles/_pix-message.scss
  addon/styles/_pix-tag.scss
  addon/styles/_pix-tooltip.scss
  addon/styles/_reset-css.scss
Labels: Tech review Needed, team-evaluation

#28 [TECH] Correction des warnings de storybook
  .storybook/manager.js
  .storybook/preview.js
  addon/stories/pix-background-header.stories.js
  addon/stories/pix-block.stories.js
  addon/stories/pix-link-back.stories.js
  addon/stories/pix-message.stories.js
  addon/stories/pix-tag.stories.js
  addon/stories/pix-tooltip.stories.js
  addon/styles/_pix-background-header.scss
  addon/styles/_pix-return-to.scss
Labels: Tech review Needed, team-acces, team-certif, team-evaluation, team-prescription
