Repository 1024pix/pix-ui, pull requests merged in 2020-06, with the labels that each got.

#10 [TECH] Ajout d'un script de déploiement de storybook sur GitHub Pages
  package-lock.json
  package.json
Labels: Tech review Needed

#2 [FEATURE] Création d'un composant Tooltip
  addon/components/pix-tooltip.hbs
  addon/components/pix-tooltip.js
  addon/stories/pix-tooltip.stories.js
  addon/styles/_pix-tooltip.scss
  addon/styles/addon.scss
  app/components/pix-tooltip.js
  tests/integration/components/pix-tooltip-test.js
Labels: Tech review Needed

#13 [TECH] Correction de l'ordre des titres du Changelog
  CHANGELOG.md
  scripts/get-pull-requests-to-release-in-prod.js
  scripts/publish.sh
Labels: Tech review Needed

#17 [FEATURE] Ajout du composant PixTag
  addon/components/pix-tag.hbs
  addon/stories/pix-tag.stories.js
  addon/styles/_pix-tag.scss
  addon/styles/addon.scss
  app/components/pix-tag.js
  tests/integration/components/pix-tag-test.js
Labels: Design review OK, Tech review OK

#18 [FEATURE] Ajout du composant Message
  addon/components/pix-message.hbs
  addon/components/pix-message.js
  addon/stories/pix-message.stories.js
  addon/styles/_pix-message.scss
  addon/styles/addon.scss
  app/components/pix-message.js
  tests/integration/components/pix-message-test.js
Labels: Design review OK, Func Review OK, Tech review OK

#20 [TECH] Mettre des dépendances en "devDependancies"
  package-lock.json
  package.json
Labels: Tech review Needed
