Repository 1024pix/pix-ui, pull requests merged in 2020-08, with the labels that each got.

#29 [FEATURE] Ajout du composant PixBanner (PIX-1114).
  addon/components/pix-banner.hbs
  addon/components/pix-banner.js
  addon/stories/pix-banner.stories.js
  addon/styles/_pix-banner.scss
  addon/styles/addon.scss
  app/components/pix-banner.js
Labels: team-prescription, 🚧 Development in progress

#30 [FEATURE] Add support for ember app internal links in PixBanner (PIX-1085).
  addon/components/pix-banner.hbs
  addon/components/pix-banner.js
  addon/stories/pix-banner.stories.js
  addon/styles/_pix-banner.scss
Labels: Func Review Needed, Tech review Needed, team-prescription

#31 [TECH] Ajout de ...attributes à la PixTooltip
  addon/components/pix-tooltip.hbs
Labels: Tech review Needed
