Repository 1024pix/pix-ui, pull requests merged in 2021-06, with the labels that each got.

#95 [FEATURE] Ajout du composant PixCollapsible
  addon/components/pix-collapsible.hbs
  addon/components/pix-collapsible.js
  addon/stories/pix-collapsible.stories.js
  addon/stories/pix-collapsible.stories.mdx
  addon/styles/_pix-collapsible.scss
  addon/styles/addon.scss
  app/components/pix-collapsible.js
  tests/integration/components/pix-collapsible-test.js
Labels: Design Review Needed, Tech review Needed, cross-team, team-acces

#101 Permettre l'absence de trigger action sur PixButton de type submit
  addon/components/pix-button.hbs
  addon/components/pix-button.js
  addon/stories/pix-button.stories.js
  tests/integration/components/pix-button-test.js
  tests/unit/components/pix-button-test.js
Labels: Tech review OK, cross-team

#102 [CLEAN] Corriger une petite coquille dans la doc de Pix-Tooltip
  addon/stories/pix-tooltip.stories.mdx
Labels: Tech review Needed, cross-team
