Repository 1024pix/pix-ui, pull requests merged in 2021-01, with the labels that each got.

#60 [TECH] Passer les stories à MDX
  .storybook/main.js
  addon/components/pix-banner.js
  addon/stories/pix-action-button.stories.js
  addon/stories/pix-action-button.stories.mdx
  addon/stories/pix-background-header.stories.js
  addon/stories/pix-background-header.stories.mdx
  addon/stories/pix-banner.stories.js
  addon/stories/pix-banner.stories.mdx
  addon/stories/pix-block.stories.js
  addon/stories/pix-block.stories.mdx
  addon/stories/pix-button-loading-white.stories.mdx
  addon/stories/pix-button.stories.js
  addon/stories/pix-filter-banner.stories.js
  addon/stories/pix-filter-banner.stories.mdx
  addon/stories/pix-message.stories.js
  addon/stories/pix-message.stories.mdx
  addon/stories/pix-multi-select.stories.js
  addon/stories/pix-multi-select.stories.mdx
  addon/stories/pix-return-to.stories.js
  addon/stories/pix-return-to.stories.mdx
  addon/stories/pix-select.stories.js
  addon/stories/pix-select.stories.mdx
  addon/stories/pix-stars.stories.mdx
  addon/stories/pix-tag.stories.js
  addon/stories/pix-tag.stories.mdx
  addon/stories/pix-tooltip.stories.js
  addon/stories/pix-tooltip.stories.mdx
  blueprints/pix-component/files/addon/stories/pix-__name__.stories.mdx
  package-lock.json
  package.json
Labels: Tech review Needed, cross-team

#62 [FEATURE] Ajout du tri des éléments dans le multi-select (PIX-1685)
  .storybook/preview.js
  addon/components/pix-multi-select.hbs
  addon/components/pix-multi-select.js
  addon/stories/pix-multi-select.stories.js
  addon/stories/pix-multi-select.stories.mdx
  tests/integration/components/pix-multi-select-test.js
Labels: Tech review OK, cross-team, team-prescription

#63 [FEATURE] Ajout du composant PixTextarea
  addon/components/pix-textarea.hbs
  addon/components/pix-textarea.js
  addon/stories/pix-textarea.stories.js
  addon/stories/pix-textarea.stories.mdx
  addon/styles/_pix-textarea.scss
  addon/styles/addon.scss
  app/components/pix-textarea.js
  tests/integration/components/pix-textarea-test.js
Labels: Design review OK, Tech review Needed, cross-team

#64 [FIX] Problème de CSS et de propagation sur le multiselect (PIX-1981)
  addon/components/pix-multi-select.hbs
  addon/components/pix-multi-select.js
  addon/styles/_pix-multi-select.scss
Labels: Func Review OK, team-prescription

#65 [STYLE] Correction du style FilterBanner et MultiSelect
  addon/components/pix-filter-banner.hbs
  addon/stories/pix-filter-banner.stories.js
  addon/stories/pix-filter-banner.stories.mdx
  addon/styles/_pix-filter-banner.scss
  addon/styles/_pix-multi-select.scss
Labels: Tech review Needed, cross-team, team-prescription

#66 [TECH] Pouvoir modifier les bords et la couleur de PixButton
  addon/components/pix-button.hbs
  addon/components/pix-button.js
  addon/stories/pix-button-border.stories.mdx
  addon/stories/pix-button-color.stories.mdx
  addon/stories/pix-button-loader.stories.mdx
  addon/stories/pix-button.stories.js
  addon/styles/_pix-button.scss
  addon/styles/addon.scss
Labels: Tech review Needed, cross-team

#69 [TECH] Ajout d'une icone facultative pour PixMessage
  addon/components/pix-message.hbs
  addon/components/pix-message.js
  addon/stories/pix-message.stories.js
  addon/stories/pix-message.stories.mdx
  addon/styles/_pix-message.scss
  tests/integration/components/pix-message-test.js
Labels: Design review OK, cross-team

#70 [TECH] Corriger les attributs pour la PixTextarea
  addon/components/pix-textarea.hbs
Labels: Tech review Needed, cross-team

#67 [TECH] Enrichir la PixActionButton - BREAKING CHANGES.
  addon/components/pix-action-button.hbs
  addon/stories/pix-action-button.stories.js
  addon/stories/pix-action-button.stories.mdx
  addon/styles/_pix-action-button.scss
Labels: Tech review OK, cross-team

#68 [TECH] Enrichir la Pix Tooltip - BREAKING CHANGES (Pix-2000).
  addon/components/pix-tooltip.hbs
  addon/components/pix-tooltip.js
  addon/stories/pix-tooltip.stories.js
  addon/stories/pix-tooltip.stories.mdx
  addon/styles/_pix-tooltip.scss
  tests/integration/components/pix-tooltip-test.js
Labels: Func Review OK, Tech review OK, cross-team, team-prescription

#72 [FEATURE] Ajout du nombre d'éléments filtrés dans le composant filter banner sur Pix-UI(pix-2031).
  addon/components/pix-filter-banner.hbs
  addon/components/pix-filter-banner.js
  addon/stories/pix-filter-banner.stories.js
  addon/styles/_pix-filter-banner.scss
  tests/integration/components/pix-filter-banner-test.js
Labels: :rocket: Ready to Merge, Design review OK, Func Review OK, Tech review OK, team-prescription
