Repository 1024pix/pix-ui, pull requests merged in 2021-12, with the labels that each got.

#177 [FEATURE] Création du composant Tag sélectionnable dans Pix UI (PIX-3757)
  .gitignore
  addon/components/pix-selectable-tag.hbs
  addon/components/pix-selectable-tag.js
  addon/styles/_pix-selectable-tag.scss
  addon/styles/addon.scss
  app/components/pix-selectable-tag.js
  app/stories/pix-selectable-tag.stories.js
  app/stories/pix-selectable-tag.stories.mdx
  tests/integration/components/pix-selectable-tag-test.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, team-prescription

#181 [BUGFIX] Corriger les explications d'utilisations du PixInputCode
  addon/components/pix-input-code.hbs
Labels: :rocket: Ready to Merge, Tech review OK, cross-team

#171 [DOC] Améliorer l'information sur l'accessibilité dans la doc de PixTooltip
  app/stories/pix-tooltip.stories.mdx
Labels: :rocket: Ready to Merge, Tech review OK, cross-team

#175 [TECH] Faire en sorte que le message d'erreur soit situé à l'intérieur de l'élément qui le compose (PIX-3829)
  addon/components/pix-input-password.hbs
  addon/components/pix-input.hbs
  addon/styles/_form.scss
  addon/styles/_pix-input-password.scss
  addon/styles/_pix-input.scss
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, cross-team

#182 [TECH] Rendre responsive la PixFilterBanner
  addon/components/pix-filter-banner.hbs
  addon/styles/_pix-filter-banner.scss
Labels: Design review OK, :rocket: Ready to Merge, Tech review OK
