Repository 1024pix/pix-ui, pull requests merged in 2021-11, with the labels that each got.

#166 [BUGFIX] Empêcher PixSelect de déborder de l'élément parent
  addon/styles/_pix-select.scss
  app/stories/pix-select.stories.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, cross-team

#165 [FIXBUG] Problème de sélection des statuts sur Firefox (PIX-3636)
  addon/components/pix-select.hbs
  addon/components/pix-select.js
  package-lock.json
  package.json
  tests/integration/components/pix-select-test.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, team-prescription

#164 [INFRA] Release npm @1024pix/pix-ui automatisée
  .github/workflows/npm-publish.yml
  README.md
  app/components/pix-background-header.js
  app/components/pix-banner.js
  app/components/pix-block.js
  app/components/pix-button-link.js
  app/components/pix-button-upload.js
  app/components/pix-button.js
  app/components/pix-collapsible.js
  app/components/pix-filter-banner.js
  app/components/pix-icon-button.js
  app/components/pix-input-code.js
  app/components/pix-input-password.js
  app/components/pix-input.js
  app/components/pix-message.js
  app/components/pix-multi-select.js
  app/components/pix-progress-gauge.js
  app/components/pix-radio-button.js
  app/components/pix-return-to.js
  app/components/pix-select.js
  app/components/pix-stars.js
  app/components/pix-tag.js
  app/components/pix-textarea.js
  app/components/pix-tooltip.js
  blueprints/pix-component/files/app/components/pix-__name__.js
  package-lock.json
  package.json
Labels: :rocket: Ready to Merge, cross-team

#172 [TECH] Monter node de version a 16.13.0
  .nvmrc
  package-lock.json
  package.json
Labels: :rocket: Ready to Merge, cross-team

#173 [TECH] Mise a jour du nom de domaine.
  CNAME
Labels: :rocket: Ready to Merge, cross-team

#158 [DOC] Suivre le déploiement de la release.
  docs/make-a-release.stories.mdx
Labels: :rocket: Ready to Merge, Tech review OK, cross-team

#174 [DOC] Mise a jour de la la méthode d'installation dans la documentation
  docs/use-install.stories.mdx
Labels: :rocket: Ready to Merge, cross-team

#147 [BUGFIX] Ajout de l'évènement onChange afin de supprimer le message d'erreur lorsque l'utilisateur modifie sa saisie (PIX-3476)
  addon/components/pix-input-password.hbs
  addon/components/pix-input-password.js
  addon/components/pix-input.hbs
  addon/components/pix-input.js
  app/stories/pix-input-password.stories.mdx
  app/stories/pix-input.stories.mdx
  tests/integration/components/pix-input-password-test.js
  tests/integration/components/pix-input-test.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, cross-team

#178 [DOC] Améliorer l'information sur les breaking changes dans Pix UI
  .storybook/preview.js
  docs/breaking-changes.stories.mdx
Labels: :rocket: Ready to Merge

#179 [TECH] Mise à jour du template de pull request pour faire apparaître plus clairement les BREAKING_CHANGES
  docs/pull_request_template.md
Labels: :rocket: Ready to Merge, cross-team
