Repository 1024pix/pix-ui, pull requests merged in 2021-09, with the labels that each got.

#129 [FEATURE] Aligner le style du PixTooltip avec le design system (PIX-3019).
  addon/components/pix-tooltip.hbs
  addon/stories/pix-tooltip.stories.js
  addon/stories/pix-tooltip.stories.mdx
  addon/styles/_pix-tooltip.scss
Labels: Tech review OK, cross-team

#131 [FEATURE] Centrer les boutons d'un formulaire par défaut
  addon/styles/_form.scss
Labels: :rocket: Ready to Merge, cross-team

#133 [TECH] Enlever le padding des section mis globalement
  addon/styles/addon.scss
Labels: :rocket: Ready to Merge, cross-team

#132 [FEATURE] Création du composant PixInputPassword (PIX-3089).
  addon/components/pix-input-password.hbs
  addon/components/pix-input-password.js
  addon/components/pix-input.hbs
  addon/components/pix-input.js
  addon/stories/form.stories.js
  addon/stories/pix-input-password.stories.js
  addon/stories/pix-input-password.stories.mdx
  addon/stories/pix-input.stories.mdx
  addon/styles/_form.scss
  addon/styles/_pix-input-password.scss
  addon/styles/_pix-input.scss
  addon/styles/addon.scss
  app/components/pix-input-password.js
  tests/integration/components/pix-input-password-test.js
Labels: :rocket: Ready to Merge, cross-team

#126 [FEATURE] Permettre d'afficher du code formatté HTML dans la tooltip
  addon/components/pix-tooltip.hbs
  addon/components/pix-tooltip.js
  addon/stories/pix-tooltip.stories.js
  addon/stories/pix-tooltip.stories.mdx
  tests/integration/components/pix-tooltip-test.js
Labels: Tech review Needed, cross-team

#130 [FEATURE] Création du composant PixRadioButton (PIX-3031).
  addon/components/pix-button.hbs
  addon/components/pix-radio-button.hbs
  addon/components/pix-radio-button.js
  addon/stories/form.stories.js
  addon/stories/form.stories.mdx
  addon/stories/pix-radio-button.stories.js
  addon/stories/pix-radio-button.stories.mdx
  addon/styles/_form.scss
  addon/styles/_pix-radio-button.scss
  addon/styles/addon.scss
  app/components/pix-radio-button.js
  tests/integration/components/pix-radio-button-test.js
Labels: :rocket: Ready to Merge, cross-team

#136 [BUGFIX] Pouvoir uploader le même nom de fichier 2 fois de suite
  addon/components/pix-button-upload.hbs
  addon/components/pix-button-upload.js
Labels: Func Review OK, Tech review OK, team-prescription, cross-team

#138 [BUGFIX] Modifier l'évènement utilisé dans PixButtonUpload
  addon/components/pix-button-upload.hbs
Labels: Func Review Needed, Tech review Needed

#137 [FEATURE] Création du composant PixInputCode (PIX-3172).
  addon/components/pix-input-code.hbs
  addon/components/pix-input-code.js
  addon/stories/pix-input-code.stories.js
  addon/stories/pix-input-code.stories.mdx
  addon/styles/_pix-input-code.scss
  addon/styles/addon.scss
  app/components/pix-input-code.js
  tests/integration/components/pix-input-code-test.js
Labels: :rocket: Ready to Merge, cross-team

#141 [DOC] Ajouter comment créer un composant dans le README
  README.md
Labels: :rocket: Ready to Merge, cross-team

#140 [TECH] Restreindre les permissions par défaut du github token
  .github/workflows/auto-merge.yml
Labels: :rocket: Ready to Merge, cross-team

#142 [TECH] Ajout du helper contains
  tests/helpers/contains.js
  tests/integration/components/pix-background-header-test.js
  tests/integration/components/pix-banner-test.js
  tests/integration/components/pix-block-test.js
  tests/integration/components/pix-button-test.js
  tests/integration/components/pix-button-upload-test.js
  tests/integration/components/pix-collapsible-test.js
  tests/integration/components/pix-filter-banner-test.js
  tests/integration/components/pix-input-password-test.js
  tests/integration/components/pix-input-test.js
  tests/integration/components/pix-message-test.js
  tests/integration/components/pix-multi-select-test.js
  tests/integration/components/pix-progress-gauge-test.js
  tests/integration/components/pix-radio-button-test.js
  tests/integration/components/pix-return-to-test.js
  tests/integration/components/pix-tag-test.js
  tests/integration/components/pix-textarea-test.js
  tests/integration/components/pix-tooltip-test.js
  tests/test-helper.js
Labels: Tech review Needed, cross-team
