Repository 1024pix/pix-ui, pull requests merged in 2021-08, with the labels that each got.

#105 [FEATURE] Ne pas pouvoir sélectionner la valeur vide du PixSelect.
  addon/components/pix-select.hbs
  addon/stories/pix-select.stories.js
  addon/stories/pix-select.stories.mdx
Labels: :rocket: Ready to Merge, Tech review OK

#106 [TECH] Voir le changelog dans storybook
  docs/changelog.stories.mdx
Labels: :rocket: Ready to Merge, cross-team

#104 [TECH] Bump des packages Storybook de 6.1.21 à 6.2.9.
  package-lock.json
  package.json
Labels: Func Review OK, Tech review OK, cross-team

#108 [TECH] Ajuster la taille des apperçus des composants dans les stories
  addon/stories/pix-background-header.stories.mdx
  addon/stories/pix-banner.stories.mdx
  addon/stories/pix-block.stories.mdx
  addon/stories/pix-button-border.stories.mdx
  addon/stories/pix-button-color.stories.mdx
  addon/stories/pix-button-disabled.stories.mdx
  addon/stories/pix-button-link.stories.mdx
  addon/stories/pix-button-loader.stories.mdx
  addon/stories/pix-button-shape.stories.mdx
  addon/stories/pix-button-size.stories.mdx
  addon/stories/pix-collapsible.stories.mdx
  addon/stories/pix-filter-banner.stories.mdx
  addon/stories/pix-icon-button.stories.mdx
  addon/stories/pix-message.stories.mdx
  addon/stories/pix-multi-select.stories.mdx
  addon/stories/pix-progress-gauge-custom.stories.mdx
  addon/stories/pix-progress-gauge-white.stories.mdx
  addon/stories/pix-progress-gauge-yellow.stories.mdx
  addon/stories/pix-return-to.stories.mdx
  addon/stories/pix-select.stories.mdx
  addon/stories/pix-stars.stories.mdx
  addon/stories/pix-tag.stories.mdx
  addon/stories/pix-textarea.stories.mdx
  addon/stories/pix-tooltip.stories.mdx
  blueprints/pix-component/files/addon/stories/pix-__name__.stories.mdx
  docs/create-component.stories.mdx
Labels: :rocket: Ready to Merge, cross-team

#109 [FEATURE] Enlever les effets visuels au survol d'un bouton disabled
  addon/stories/pix-button.stories.js
  addon/styles/_pix-button.scss
Labels: Tech review Needed, cross-team

#110 [FEATURE] Centrer le contenu de Pix-Button par défaut
  addon/styles/_pix-button.scss
Labels: Tech review Needed, cross-team

#111 [FEATURE] Refacto des stories
  addon/components/pix-button.hbs
  addon/components/pix-button.js
  addon/stories/pix-block.stories.js
  addon/stories/pix-block.stories.mdx
  addon/stories/pix-button-border.stories.mdx
  addon/stories/pix-button-color.stories.mdx
  addon/stories/pix-button-disabled.stories.mdx
  addon/stories/pix-button-link.stories.mdx
  addon/stories/pix-button-loader.stories.mdx
  addon/stories/pix-button-shape.stories.mdx
  addon/stories/pix-button-size.stories.mdx
  addon/stories/pix-button.stories.js
  addon/stories/pix-button.stories.mdx
  addon/stories/pix-filter-banner.stories.js
  addon/stories/pix-filter-banner.stories.mdx
  addon/stories/pix-multi-select.stories.js
  addon/stories/pix-multi-select.stories.mdx
  addon/stories/pix-progress-gauge-custom.stories.mdx
  addon/stories/pix-progress-gauge-yellow.stories.mdx
  addon/stories/pix-progress-gauge.stories.js
  addon/stories/pix-progress-gauge.stories.mdx
  addon/stories/pix-return-to.stories.js
  addon/stories/pix-return-to.stories.mdx
  addon/stories/pix-select.stories.js
  addon/stories/pix-select.stories.mdx
  addon/stories/pix-tag.stories.js
  addon/stories/pix-textarea.stories.mdx
Labels: :rocket: Ready to Merge, cross-team

#113 [TECH] Automerge la PR à l'ajout du label (PIX-3001).
  .github/workflows/auto-merge.yml
  .github/workflows/on-dev-merge.yml
Labels: Tech review Needed, cross-team

#115 [TECH] Réparer le merge automatique (PIX-3001).
  .github/workflows/auto-merge.yml
Labels: Tech review Needed, cross-team

#117 [BUGFIX] Permettre de passer des paramètres au PixButton de type lien (PIX-3036).
  addon/components/pix-button.hbs
  addon/components/pix-button.js
  addon/stories/pix-button.stories.js
  addon/stories/pix-button.stories.mdx
  tests/integration/components/pix-button-test.js
  tests/unit/components/pix-button-test.js
Labels: Tech review Needed, cross-team

#116 [TECH] S'assurer des règles d'a11y du linter (PIX-3033)
  .template-lintrc.js
  package-lock.json
  package.json
Labels: :rocket: Ready to Merge, Tech review OK, cross-team

#114 [TECH] Mise a jour des dépendances et fix des vulnérabilités (PIX-2961).
  package-lock.json
  package.json
Labels: Tech review Needed, cross-team

#118 [FEATURE] Alignement du PixButton avec le design system
  .storybook/fonts.css
  .storybook/preview.js
  addon/components/pix-button.hbs
  addon/components/pix-button.js
  addon/stories/pix-button.stories.js
  addon/stories/pix-button.stories.mdx
  addon/styles/_pix-button.scss
  tests/integration/components/pix-button-test.js
Labels: Func Review Needed, Tech review Needed, cross-team

#119 [FEATURE] Ajout du composant PixButtonLink
  addon/components/pix-button-base.js
  addon/components/pix-button-link.hbs
  addon/components/pix-button-link.js
  addon/components/pix-button.js
  addon/stories/pix-button-link.stories.js
  addon/stories/pix-button-link.stories.mdx
  addon/stories/pix-button.stories.js
  addon/stories/pix-button.stories.mdx
  addon/styles/_pix-button-base.scss
  addon/styles/_pix-button-link.scss
  addon/styles/_pix-button.scss
  addon/styles/addon.scss
  app/components/pix-button-link.js
  tests/dummy/app/router.js
  tests/integration/components/pix-button-link-test.js
Labels: Tech review Needed, cross-team

#120 [FEATURE] Ajout du composant PixButtonUpload
  addon/components/pix-button-upload.hbs
  addon/components/pix-button-upload.js
  addon/stories/pix-button-upload.stories.js
  addon/stories/pix-button-upload.stories.mdx
  addon/styles/_pix-button-upload.scss
  addon/styles/addon.scss
  app/components/pix-button-upload.js
  tests/integration/components/pix-button-upload-test.js
Labels: Tech review Needed, cross-team

#125 [FEATURE] Ne pas afficher la tooltip si le texte est vide
  addon/components/pix-tooltip.hbs
  addon/stories/pix-tooltip.stories.js
  addon/stories/pix-tooltip.stories.mdx
  tests/integration/components/pix-tooltip-test.js
Labels: Tech review Needed, cross-team

#121 [FEATURE] Création du composant PixInput (PIX-3014).
  addon/components/pix-input.hbs
  addon/components/pix-input.js
  addon/stories/pix-input.stories.js
  addon/stories/pix-input.stories.mdx
  addon/styles/_pix-input.scss
  addon/styles/addon.scss
  app/components/pix-input.js
  tests/integration/components/pix-input-test.js
Labels: Design Review Needed, Tech review Needed, cross-team

#128 [FEATURE] Aligner le style du PixBanner avec le design system (PIX-3022).
  addon/stories/pix-banner.stories.js
  addon/stories/pix-banner.stories.mdx
  addon/styles/_breakpoints.scss
  addon/styles/_colors.scss
  addon/styles/_pix-banner.scss
  addon/styles/_spacing.scss
  addon/styles/addon.scss
Labels: Design Review Needed, Tech review Needed, cross-team

#122 [TECH] Aligner le style des composants de formulaire avec le design system (PIX-3052).
  addon/components/pix-multi-select.hbs
  addon/components/pix-multi-select.js
  addon/components/pix-select.hbs
  addon/components/pix-select.js
  addon/components/pix-textarea.hbs
  addon/components/pix-textarea.js
  addon/stories/form.stories.js
  addon/stories/form.stories.mdx
  addon/stories/pix-input.stories.mdx
  addon/stories/pix-multi-select.stories.js
  addon/stories/pix-select.stories.js
  addon/stories/pix-select.stories.mdx
  addon/stories/pix-textarea.stories.js
  addon/stories/pix-textarea.stories.mdx
  addon/styles/_form.scss
  addon/styles/_pix-button-base.scss
  addon/styles/_pix-input.scss
  addon/styles/_pix-multi-select.scss
  addon/styles/_pix-select.scss
  addon/styles/_pix-textarea.scss
  addon/styles/addon.scss
  tests/integration/components/pix-multi-select-test.js
  tests/integration/components/pix-select-test.js
  tests/integration/components/pix-textarea-test.js
Labels: Tech review OK, cross-team
