Repository 1024pix/pix-ui, pull requests merged in 2021-03, with the labels that each got.

#86 Informer tout le monde que l'apperçu du multiselect dans storybook ne fonctionne pas
  addon/stories/pix-multi-select.stories.js
  addon/stories/pix-multi-select.stories.mdx
Labels: Tech review Needed, cross-team

#84 [TECH] Mettre à jour les dépendances de Pix-UI
  addon/components/pix-multi-select.hbs
  addon/components/pix-textarea.hbs
  package-lock.json
  package.json
Labels: Tech review Needed, cross-team

#83 [FEATURE] Rendre PixSelect cherchable (PIX-2306)
  addon/components/pix-select.hbs
  addon/components/pix-select.js
  addon/stories/pix-select.stories.js
  addon/stories/pix-select.stories.mdx
  addon/styles/_pix-select.scss
  tests/integration/components/pix-select-test.js
Labels: Design Review Needed, Tech review Needed, cross-team, team-certif

#89 [TECH] Déployer Storybook avec une GitHub action
  .github/workflows/deploy-storybook.yml
Labels: :rocket: Ready to Merge, cross-team

#91 [TECH] Ajout de review app pour Storybook
  .buildpacks
  package.json
  scalingo.json
  scripts/build.sh
  scripts/signal-deploy-to-pr.sh
  servers.conf.erb
Labels: Func Review Needed, Tech review Needed, cross-team
