Repository 1024pix/pix-ui, pull requests merged in 2021-02, with the labels that each got.

#73 [TECH] Toujours passer ...attributes à la PixTextarea
  addon/components/pix-textarea.hbs
  tests/integration/components/pix-textarea-test.js
Labels: Tech review Needed, cross-team

#71 [STYLE] Corriger l'affichage d'un texte sur deux lignes avec une icone dans PixMessage
  addon/components/pix-message.hbs
  addon/stories/pix-button-border.stories.mdx
  addon/stories/pix-message.stories.js
  addon/stories/pix-message.stories.mdx
  addon/styles/_pix-message.scss
Labels: :rocket: Ready to Merge, cross-team

#75 [TECH] Permettre le redimensionnement de la textarea seulement vertical
  addon/styles/_pix-textarea.scss
Labels: Tech review Needed, cross-team

#77 [TECH] Pouvoir désactiver le PixButton
  addon/components/pix-button.hbs
  addon/components/pix-button.js
  addon/stories/pix-button-disabled.stories.mdx
  addon/stories/pix-button.stories.js
  addon/styles/_pix-button.scss
  tests/integration/components/pix-button-test.js
Labels: Tech review Needed, cross-team

#74 [FEATURE] Ajout d'un bouton permettant de supprimer tous les éléments filtrés d'un seul clic dans le filter banner(PIX-2032).
  addon/components/pix-filter-banner.hbs
  addon/components/pix-filter-banner.js
  addon/stories/pix-filter-banner.stories.js
  addon/styles/_pix-filter-banner.scss
  package-lock.json
  package.json
  tests/integration/components/pix-filter-banner-test.js
Labels: Func Review OK, Tech review OK, team-prescription

#76 [FIX] Multi-select: le composant ne se met pas a jour quand on modifie l'argument '@selected' (PIX-2141)
  addon/components/pix-multi-select.hbs
  addon/components/pix-multi-select.js
  tests/integration/components/pix-multi-select-test.js
Labels: Func Review OK, Tech review OK

#79 [TECH] Enrichir PixActionButton et la renommer en PixIconButton pour que cela reflète plus son utilisation - BREAKING CHANGES.
  addon/components/pix-action-button.hbs
  addon/components/pix-icon-button.hbs
  addon/components/pix-icon-button.js
  addon/stories/pix-action-button.stories.mdx
  addon/stories/pix-icon-button.stories.js
  addon/stories/pix-icon-button.stories.mdx
  addon/styles/_pix-action-button.scss
  addon/styles/_pix-icon-button.scss
  addon/styles/addon.scss
  app/components/pix-action-button.js
  app/components/pix-icon-button.js
  tests/integration/components/pix-action-button-test.js
  tests/integration/components/pix-icon-button-test.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech review OK, cross-team, team-prescription

#78 [FEAT] Mise à jour de la couleur de l'élément bannière.
  .storybook/storybook-custom-theme.js
  addon/styles/_colors.scss
Labels: team-evaluation
