Repository 1024pix/pix-ui, pull requests merged in 2022-07, with the labels that each got.

#224 [TECH] Fixer la version NodeJS à 16.14.0
  .circleci/config.yml
  .nvmrc
  package-lock.json
  package.json
Labels: :rocket: Ready to Merge, Tech review OK, cross-team

#229 [TECH] Retirer la taille par defaut du composant PixMultiSelect
  addon/styles/_pix-multi-select.scss
  addon/styles/_pix-select.scss
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, cross-team

#231 [BUGFIX] PixButton de type submit affiche un loader si @isLoading=true
  addon/components/pix-button.hbs
  addon/components/pix-button.js
  app/stories/pix-button.stories.js
  tests/integration/components/pix-button-test.js
  tests/unit/components/pix-button-test.js
Labels: :rocket: Ready to Merge, Tech review OK, cross-team

#234 [BUGFIX] Laisser les filtres à côté du label dans le FilterBanner (PIX-5301)
  addon/styles/_pix-filter-banner.scss
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, team-prescription, cross-team

#236 [BUGFIX] Correction du déploiement de Storybook
  .github/workflows/deploy-storybook.yml
Labels: :rocket: Ready to Merge, Tech review OK, cross-team

#237 [TECH] Changer les pré-requis engine du package.json (PIX-5319)
  package.json
Labels: :rocket: Ready to Merge, Tech review OK, cross-team

#238 [TECH] Monter de version fontawesome (PIX-5325)
  addon/components/pix-banner.hbs
  addon/components/pix-banner.js
  addon/components/pix-dropdown.hbs
  addon/components/pix-filter-banner.hbs
  addon/components/pix-input-password.hbs
  addon/components/pix-input.hbs
  addon/components/pix-message.js
  addon/components/pix-modal.hbs
  addon/components/pix-multi-select.hbs
  app/stories/pix-icon-button.stories.js
  app/stories/pix-icon-button.stories.mdx
  app/stories/pix-tooltip.stories.js
  app/stories/pix-tooltip.stories.mdx
  package-lock.json
  package.json
  tests/integration/components/pix-icon-button-test.js
  tests/integration/components/pix-message-test.js
Labels: Func Review OK, :rocket: Ready to Merge
