Repository 1024pix/pix-ui, pull requests merged in 2022-12, with the labels that each got.

#290 [FEATURE] Ajoute une propriété id sur le composant PixSelect (PIX-6440)
  addon/components/pix-select.hbs
  addon/components/pix-select.js
  app/stories/pix-select.stories.js
  app/stories/pix-select.stories.mdx
  tests/integration/components/pix-select-test.js
  tests/unit/components/pix-select-test.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, team-prescription

#291 [FEATURE] Ajoute la possibilité d'utiliser un block à la place du placeholder (PIX-6443)
  addon/components/pix-multi-select.hbs
  addon/components/pix-multi-select.js
  addon/styles/_pix-multi-select.scss
  app/stories/pix-multi-select.stories.js
  app/stories/pix-multi-select.stories.mdx
  tests/integration/components/pix-multi-select-test.js
  tests/unit/components/pix-multi-select-test.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, team-prescription

#274 [TECH] Utiliser la dernière version mineure de NodeJs automatiquement
  package-lock.json
  package.json
Labels: :rocket: Ready to Merge, Tech review OK, cross-team

#296 [BUGFIX] Le select ne prend pas le focus quand on clique sur son label (PIX-6476).
  addon/components/pix-multi-select.hbs
  addon/components/pix-multi-select.js
  tests/integration/components/pix-multi-select-test.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, team-prescription

#292 [TECH] Mettre à jour `ember-source` vers la 4.0.1 (PIX-6462).
  .npmignore
  .storybook/main.js
  README.md
  config/ember-try.js
  ember-cli-build.js
  package-lock.json
  package.json
  tests/dummy/app/router.js
  tests/dummy/app/templates/application.hbs
  tests/dummy/config/ember-cli-update.json
  tests/dummy/config/targets.js
  tests/index.html
  tests/integration/components/pix-button-test.js
  tests/integration/components/pix-filterable-and-searchable-select-test.js
  tests/integration/components/pix-icon-button-test.js
  tests/integration/components/pix-multi-select-test.js
  tests/integration/components/pix-select-test.js
  tests/test-helper.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, team-rocket

#288 [FEATURE] Ajout le composant PixToggle (PIX-6427)
  addon/components/pix-toggle.hbs
  addon/components/pix-toggle.js
  addon/styles/_pix-toggle.scss
  addon/styles/addon.scss
  app/components/pix-toggle.js
  app/stories/pix-toggle.stories.js
  app/stories/pix-toggle.stories.mdx
  tests/integration/components/pix-toggle-test.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, cross-team

#300 [TECH] Réparer l'affichage des stories
  app/stories/form.stories.js
  app/stories/pix-banner.stories.js
  app/stories/pix-block.stories.js
  app/stories/pix-button-link.stories.js
  app/stories/pix-button-upload.stories.js
  app/stories/pix-button.stories.js
  app/stories/pix-checkbox.stories.js
  app/stories/pix-collapsible.stories.js
  app/stories/pix-dropdown.stories.js
  app/stories/pix-filter-banner.stories.js
  app/stories/pix-filterable-and-searchable-select.stories.js
  app/stories/pix-icon-button.stories.js
  app/stories/pix-input-code.stories.js
  app/stories/pix-input-password.stories.js
  app/stories/pix-input.stories.js
  app/stories/pix-message.stories.js
  app/stories/pix-modal.stories.js
  app/stories/pix-pagination.stories.js
  app/stories/pix-progress-gauge.stories.js
  app/stories/pix-radio-button.stories.js
  app/stories/pix-return-to.stories.js
  app/stories/pix-selectable-tag.stories.js
  app/stories/pix-sidebar.stories.js
  app/stories/pix-stars.stories.js
  app/stories/pix-tag.stories.js
  app/stories/pix-textarea.stories.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK

#287 [FEATURE] Améliorer l'accessiblité de PixSidebar (PIX-6424)
  addon/components/pix-sidebar.hbs
  tests/integration/components/pix-sidebar-test.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, team-evaluation

#285 [FEATURE] Améliorer l'accessibilité de PixModal (PIX-6265)
  addon/components/pix-modal.hbs
  addon/styles/_pix-modal.scss
  app/stories/pix-modal.stories.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, team-evaluation

#302 [DOCS] Modifie l'exemple de la Modal pour utiliser `gap`
  app/stories/pix-modal.stories.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, team-evaluation

#304 [TECH] Enlever le reset-css et ajouter attributes dans PixSelect(PIX-6504)
  .storybook/preview.js
  addon/components/pix-pagination.hbs
  addon/components/pix-pagination.js
  addon/components/pix-select.hbs
  addon/styles/_pix-filter-banner.scss
  addon/styles/_pix-select.scss
  app/stories/form.stories.mdx
  app/stories/pix-background-header.stories.mdx
  app/stories/pix-banner.stories.mdx
  app/stories/pix-block.stories.mdx
  app/stories/pix-button-link.stories.mdx
  app/stories/pix-button-upload.stories.mdx
  app/stories/pix-button.stories.mdx
  app/stories/pix-checkbox.stories.mdx
  app/stories/pix-collapsible.stories.mdx
  app/stories/pix-dropdown.stories.mdx
  app/stories/pix-filter-banner.stories.js
  app/stories/pix-filter-banner.stories.mdx
  app/stories/pix-filterable-and-searchable-select.stories.js
  app/stories/pix-icon-button.stories.mdx
  app/stories/pix-input-code.stories.mdx
  app/stories/pix-input-password.stories.mdx
  app/stories/pix-input.stories.mdx
  app/stories/pix-message.stories.mdx
  app/stories/pix-modal.stories.mdx
  app/stories/pix-multi-select.stories.js
  app/stories/pix-multi-select.stories.mdx
  app/stories/pix-pagination.stories.mdx
  app/stories/pix-progress-gauge.stories.mdx
  app/stories/pix-radio-button.stories.mdx
  app/stories/pix-return-to.stories.mdx
  app/stories/pix-select.stories.js
  app/stories/pix-select.stories.mdx
  app/stories/pix-selectable-tag.stories.mdx
  app/stories/pix-sidebar.stories.mdx
  app/stories/pix-stars.stories.mdx
  app/stories/pix-tag.stories.mdx
  app/stories/pix-textarea.stories.mdx
  app/stories/pix-toggle.stories.mdx
  app/stories/pix-tooltip.stories.mdx
  blueprints/pix-component/files/app/stories/pix-__name__.stories.mdx
  docs/create-component.stories.mdx
  package-lock.json
  package.json
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, team-prescription

#305 [FEATURE] Permettre l'appel d'une fonction lors de la fermeture d'une Pix Banner (PIX-6513).
  addon/components/pix-banner.js
  app/stories/pix-banner.stories.js
  app/stories/pix-banner.stories.mdx
  tests/unit/components/pix-banner-test.js
Labels: :rocket: Ready to Merge, Tech review OK, team-acces

#270 [TECH] Suppression ember-cli-google-fonts (PIX-6423)
  package-lock.json
  package.json
Labels: :rocket: Ready to Merge, Tech review OK, cross-team

#310 [DOCS] Ajout infos v20.2.4 au changelog
  CHANGELOG.md
Labels: :rocket: Ready to Merge, Tech review OK, cross-team

#308 [BUGFIX] Support de l'état `disabled` et correction de la taille de l'élement Pix Select
  addon/components/pix-select.hbs
  addon/components/pix-select.js
  addon/styles/_form.scss
  addon/styles/_pix-select.scss
  app/stories/pix-select.stories.js
  tests/integration/components/pix-select-test.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, cross-team

#271 [FEATURE] Revue du design des boutons (PIX-6218)
  addon/styles/_colors.scss
  addon/styles/_pix-banner.scss
  addon/styles/_pix-button-base.scss
  addon/styles/_pix-icon-button.scss
Labels: Design review OK, Func Review OK, :rocket: Ready to Merge, Tech review OK, cross-team

#312 [BUGFIX] Supprime la zone blanche non clickable dans les options du `PixSelect` (PIX-6591)
  addon/styles/_pix-select.scss
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, team-evaluation, team-acces, team-prescription

#307 [FEATURE] Création du composant carte (PIX-6141).
  addon/components/pix-indicator-card.hbs
  addon/components/pix-indicator-card.js
  addon/styles/_pix-indicator-card.scss
  addon/styles/addon.scss
  addon/utils/accessible-contrasted-color-generator.js
  app/components/pix-indicator-card.js
  app/stories/pix-block.stories.mdx
  app/stories/pix-indicator-card.stories.js
  app/stories/pix-indicator-card.stories.mdx
  ember-cli-build.js
  package-lock.json
  package.json
  tests/integration/components/pix-indicator-card-test.js
  tests/unit/utils/accessible-contrasted-color-generator-test.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, team-prescription

#313 [TECH] Ne plus ajouter de lien vers la review-app dans la pull-request
  package.json
  scripts/signal-deploy-to-pr.sh
Labels: :rocket: Ready to Merge, Tech review OK, team-captains
