Repository 1024pix/pix-ui, pull requests merged in 2022-11, with the labels that each got.

#276 [BUGFIX] Corriger le rendu du composant tootltip dans des contextes flex (PIX-6314)
  addon/components/pix-tooltip-deprecated.hbs
  addon/components/pix-tooltip-deprecated.js
  addon/components/pix-tooltip.hbs
  addon/styles/_pix-tooltip.scss
  app/components/pix-tooltip-deprecated.js
  app/stories/pix-tooltip-deprecated.stories.js
  app/stories/pix-tooltip-deprecated.stories.mdx
  tests/integration/components/pix-tooltip-test.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, team-prescription, team-rocket

#266 [BREAKING CHANGES][FEATURE] Créer un nouveau PixSelect accessible basé sur PixDropdown/PixSelect (Pix-6018)
  addon/components/pix-pagination.hbs
  addon/components/pix-select.hbs
  addon/components/pix-select.js
  addon/styles/_form.scss
  addon/styles/_pix-select.scss
  app/modifiers/on-arrow-down-up-action.js
  app/modifiers/on-enter-action.js
  app/modifiers/on-space-action.js
  app/stories/pix-select.stories.js
  app/stories/pix-select.stories.mdx
  tests/integration/components/pix-select-test.js
  tests/unit/components/pix-select-test.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK

#280 [BUG] Empêche le composant PixSelect de capturer le focus à chaque click sur la page (PIX-6397)
  addon/components/pix-select.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, team-prescription

#281 [BUGFIX] Autorise d'autres événements de la page à avoir lieu lors de l'ouverture/fermeture du select (PIX-6399)
  addon/components/pix-select.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, team-prescription
