Repository 1024pix/pix-ui, pull requests merged in 2022-01, with the labels that each got.

#185 [A11Y] Ajouter une nouvelle couleur dans la palette de PixTag (PIX-4109)
  addon/styles/_colors.scss
  addon/styles/_pix-tag.scss
  app/stories/pix-tag.stories.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, team-prescription

#94 [FEATURE] Ajout du composant PixModal
  addon/components/pix-modal.hbs
  addon/components/pix-modal.js
  addon/styles/_pix-modal.scss
  addon/styles/addon.scss
  app/components/pix-modal-content.js
  app/components/pix-modal-footer.js
  app/components/pix-modal.js
  app/stories/pix-modal.stories.js
  app/stories/pix-modal.stories.mdx
  blueprints/pix-component/files/app/stories/pix-__name__.stories.mdx
  docs/test-component-without-release.stories.mdx
  tests/integration/components/pix-modal-test.js
Labels: Design review OK, :rocket: Ready to Merge, cross-team

#187 [BUGFIX] Rendre tout le tag sélectionnable (PIX-4179)
  addon/styles/_pix-selectable-tag.scss
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, team-prescription

#186 [BUGFIX] Désactiver l'autocomplete sur le composant Pix Select (PIX-4158)
  addon/components/pix-select.hbs
  tests/integration/components/pix-select-test.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, team-prescription

#188 [BREAKING_CHANGES] Input / InputPassword missing event on onChange (PIX-4243)
  addon/components/pix-input-password.hbs
  addon/components/pix-input-password.js
  addon/components/pix-input.hbs
  addon/components/pix-input.js
  addon/styles/_pix-input.scss
  app/stories/pix-input-password.stories.mdx
  app/stories/pix-input.stories.mdx
  tests/integration/components/pix-input-password-test.js
  tests/integration/components/pix-input-test.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, team-prescription, cross-team, :warning: BREAKING CHANGES :warning:
