Repository 1024pix/pix-ui, pull requests merged in 2022-04, with the labels that each got.

#207 [FEATURE] Permettre à pix-pagination d'avoir une version condensée (PIX-4715)
  addon/components/pix-pagination.hbs
  addon/components/pix-pagination.js
  addon/styles/_pix-pagination.scss
  app/stories/pix-pagination.stories.js
  app/stories/pix-pagination.stories.mdx
  tests/integration/components/pix-pagination-test.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, team-evaluation

#208 [TECH] Suppression de la margin dans Pix-Pagination (PIX-4733)
  addon/styles/_pix-pagination.scss
Labels: Design review OK, :rocket: Ready to Merge, team-evaluation

#209 [BUGFIX] Remplace la page courante si elle n'existe plus
  addon/components/pix-pagination.hbs
  addon/components/pix-pagination.js
  package-lock.json
  package.json
Labels: Func Review OK, :rocket: Ready to Merge, team-evaluation

#204 [FEATURE] Permettre de rendre Pix Input et Pix Input Password obligatoires (PIX-4138).
  addon/components/pix-input-password.hbs
  addon/components/pix-input.hbs
  app/stories/form.stories.js
  app/stories/pix-input-password.stories.js
  app/stories/pix-input-password.stories.mdx
  app/stories/pix-input.stories.js
  app/stories/pix-input.stories.mdx
  tests/integration/components/pix-input-password-test.js
  tests/integration/components/pix-input-test.js
Labels: :rocket: Ready to Merge, cross-team

#211 [BUGFIX] Ne permettre qu'un label dans les composants Pix Input et Input Password (PIX-4125).
  addon/components/pix-input-password.hbs
  addon/components/pix-input.hbs
  addon/styles/_pix-input.scss
  app/stories/form.stories.js
  app/stories/form.stories.mdx
Labels: :rocket: Ready to Merge, cross-team

#212 [BUGFIX] Ajouter un aria-label au Pix Input (PIX-4759).
  addon/components/pix-input.hbs
  addon/components/pix-input.js
  app/stories/pix-input-password.stories.js
  app/stories/pix-input.stories.js
  app/stories/pix-input.stories.mdx
  tests/integration/components/pix-input-test.js
Labels: :rocket: Ready to Merge, cross-team, :warning: BREAKING CHANGES :warning:

#213 [FEATURE] Retirer l'option d'ajouter une icône dans le composant Pix Input (PIX-4766).
  addon/components/pix-input.hbs
  addon/components/pix-input.js
  addon/styles/_pix-input.scss
  app/stories/pix-input.stories.js
  app/stories/pix-input.stories.mdx
  tests/integration/components/pix-input-test.js
Labels: :rocket: Ready to Merge, cross-team

#214 [BUGFIX] Ajouter params à la méthode triggerAction à PixIconButton (PIX-4790)
  addon/components/pix-icon-button.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, team-prescription
