Repository 1024pix/pix-ui, pull requests merged in 2022-06, with the labels that each got.

#220 Mise à jour de la doc pour tester pixInput via testing-library
  app/stories/pix-input.stories.mdx
Labels: Tech review Needed, cross-team

#219 [TECH] Ajouter les variables du design system dans Pix-UI.(PIX-2307)
  addon/styles/_colors.scss
  addon/styles/_form.scss
  addon/styles/_pix-background-header.scss
  addon/styles/_pix-banner.scss
  addon/styles/_pix-block.scss
  addon/styles/_pix-button-base.scss
  addon/styles/_pix-button-link.scss
  addon/styles/_pix-button.scss
  addon/styles/_pix-collapsible.scss
  addon/styles/_pix-dropdown.scss
  addon/styles/_pix-filter-banner.scss
  addon/styles/_pix-icon-button.scss
  addon/styles/_pix-input-code.scss
  addon/styles/_pix-input-password.scss
  addon/styles/_pix-input.scss
  addon/styles/_pix-message.scss
  addon/styles/_pix-modal.scss
  addon/styles/_pix-multi-select.scss
  addon/styles/_pix-pagination.scss
  addon/styles/_pix-progress-gauge.scss
  addon/styles/_pix-radio-button.scss
  addon/styles/_pix-return-to.scss
  addon/styles/_pix-select.scss
  addon/styles/_pix-selectable-tag.scss
  addon/styles/_pix-stars.scss
  addon/styles/_pix-tag.scss
  addon/styles/_pix-textarea.scss
  addon/styles/_pix-tooltip.scss
  addon/styles/_typography.scss
  docs/design-tokens.stories.mdx
  docs/pix-design-tokens-dev.stories.mdx
Labels: Func Review OK, :rocket: Ready to Merge, cross-team

#223 [DOC] Ajouter la palette des couleurs & la documentation pour les couleurs (PIX-5181) .
  addon/styles/_colors.scss
  docs/colors-palette.stories.mdx
  docs/design-tokens.stories.mdx
  docs/pix-design-tokens.stories.mdx
Labels: Func Review OK, :rocket: Ready to Merge, cross-team

#225 [FEATURE] Rendre le contenu de PixCollapsible en lazy
  addon/components/pix-collapsible.hbs
  addon/components/pix-collapsible.js
  tests/integration/components/pix-collapsible-test.js
Labels: :rocket: Ready to Merge, Tech review OK, cross-team

#226 [TECH] Permettre le passage en multi ligne du bandeau (PIX-5213)
  addon/components/pix-filter-banner.hbs
  addon/components/pix-filter-banner.js
  addon/styles/_pix-filter-banner.scss
  addon/styles/_pix-select.scss
  app/stories/pix-filter-banner.stories.js
  app/stories/pix-filter-banner.stories.mdx
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, team-prescription

#228 [TECH] Import et utilisation des polices Google Fonts dans le projet
  .gitignore
  .storybook/fonts.css
  .storybook/preview.js
  addon/styles/_fonts.scss
  public/fonts/OpenSans/OpenSans-Light.ttf
  public/fonts/OpenSans/OpenSans-Regular.ttf
  public/fonts/OpenSans/OpenSans-SemiBold.ttf
  public/fonts/Roboto/Roboto-Light.ttf
  public/fonts/Roboto/Roboto-Medium.ttf
  public/fonts/Roboto/Roboto-Regular.ttf
Labels: :rocket: Ready to Merge
