Repository 1024pix/pix-ui, pull requests merged in 2022-09, with the labels that each got.

#246 [BUGFIX] Mettre le focus sur le premier élement où est utiliser le `trap-focus`.
  addon/components/pix-modal.hbs
  addon/components/pix-sidebar.hbs
  addon/styles/_pix-modal.scss
  app/modifiers/trap-focus.js
  app/stories/pix-modal.stories.js
  app/stories/pix-modal.stories.mdx
  app/stories/pix-sidebar.stories.js
  tests/integration/components/pix-modal-test.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK

#248 [BUGFIX] Prévenir des erreurs à la première ouverture de la sidebar/modal
  app/modifiers/trap-focus.js
Labels: :rocket: Ready to Merge, Tech review OK

#249 [BUGFIX] Permettre le controle des checkboxs
  addon/components/pix-checkbox.hbs
  app/stories/pix-checkbox.stories.js
  tests/integration/components/pix-checkbox-test.js
Labels: :rocket: Ready to Merge

#251 [BUGFIX] Évite de casser les tests d'acceptance des applis (PIX-5619)
  addon/components/pix-modal.hbs
  addon/components/pix-modal.js
  addon/components/pix-sidebar.hbs
  addon/components/pix-sidebar.js
  app/stories/pix-sidebar.stories.js
  tests/acceptance/pix-modal-page-test.js
  tests/acceptance/pix-sidebar-page-test.js
  tests/dummy/app/controllers/.gitkeep
  tests/dummy/app/controllers/modal-page.js
  tests/dummy/app/controllers/sidebar-page.js
  tests/dummy/app/router.js
  tests/dummy/app/templates/modal-page.hbs
  tests/dummy/app/templates/sidebar-page.hbs
  tests/helpers/wait-for.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, team-evaluation

#255 [FEATURE] Améliorer l'accessibilité de Pix-Modal.
  addon/components/pix-modal.hbs
  addon/components/pix-modal.js
  addon/styles/_pix-modal.scss
  app/stories/pix-modal.stories.js
Labels: Func Review OK, :rocket: Ready to Merge, team-evaluation

#252 [FEATURE] Rendre accessible (a11y) le composant PixMultiSelect (PIX-5555)
  addon/components/pix-checkbox.hbs
  addon/components/pix-checkbox.js
  addon/components/pix-multi-select.hbs
  addon/components/pix-multi-select.js
  addon/styles/_a11y.scss
  addon/styles/_form.scss
  addon/styles/_pix-checkbox.scss
  addon/styles/_pix-multi-select.scss
  addon/styles/_pix-stars.scss
  addon/styles/addon.scss
  app/modifiers/on-arrow-down-up-action.js
  app/modifiers/on-enter-action.js
  app/modifiers/on-escape-action.js
  app/modifiers/trap-focus.js
  app/stories/form.stories.js
  app/stories/pix-checkbox.stories.js
  app/stories/pix-checkbox.stories.mdx
  app/stories/pix-multi-select.stories.js
  app/stories/pix-multi-select.stories.mdx
  package-lock.json
  package.json
  tests/integration/components/pix-checkbox-test.js
  tests/integration/components/pix-multi-select-test.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, cross-team, :warning: BREAKING CHANGES :warning:

#256 [BUFGIX] Mettre à jour la page d'utilisation de la PixModal (PIX-5735)
  app/stories/pix-modal.stories.js
  app/stories/pix-modal.stories.mdx
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, cross-team

#257 [FEATURE] Suppression du `padding` de la Sidebar pour permettre de mieux customiser
  addon/styles/_pix-sidebar.scss
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, team-evaluation
