Repository 1024pix/pix-ui, pull requests merged in 2022-08, with the labels that each got.

#232 [FEATURE] Ajout du composant checkbox (PIX-3030)
  addon/components/pix-checkbox.hbs
  addon/components/pix-checkbox.js
  addon/styles/_pix-checkbox.scss
  addon/styles/addon.scss
  app/components/pix-checkbox.js
  app/stories/form.stories.js
  app/stories/pix-checkbox.stories.js
  app/stories/pix-checkbox.stories.mdx
  tests/integration/components/pix-checkbox-test.js
Labels: :rocket: Ready to Merge, team-acces, cross-team

#239 [BREAKING_CHANGES][BUGFIX] Correction des couleurs du design system par rapport à Figma (PIX-5331).
  addon/styles/_colors.scss
  addon/styles/_pix-banner.scss
  addon/styles/_pix-message.scss
  docs/colors-palette.stories.mdx
  docs/design-tokens.stories.mdx
Labels: Design review OK, :rocket: Ready to Merge, team-evaluation, cross-team, :warning: BREAKING CHANGES :warning:

#244 [FEATURE] PixModal : ajouter des modifiers trap-focus et action au echap (PIX-5157)
  addon/components/pix-modal.hbs
  addon/components/pix-modal.js
  app/modifiers/on-escape-action.js
  app/modifiers/trap-focus.js
  app/stories/pix-modal.stories.js
  app/stories/pix-modal.stories.mdx
  tests/integration/modifiers/on-escape-action-test.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK

#245 [FEATURE] Ajouter un composant Sidebar (PIX-4298)
  addon/components/pix-sidebar.hbs
  addon/components/pix-sidebar.js
  addon/styles/_pix-sidebar.scss
  addon/styles/addon.scss
  app/components/pix-sidebar.js
  app/stories/pix-sidebar.stories.js
  app/stories/pix-sidebar.stories.mdx
  tests/integration/components/pix-sidebar-test.js
Labels: :rocket: Ready to Merge, Tech review OK, team-evaluation

#247 [FEATURE] Amélioration couleurs `PixIconButton`
  addon/styles/_pix-banner.scss
  addon/styles/_pix-icon-button.scss
  app/stories/pix-icon-button.stories.js
  app/stories/pix-icon-button.stories.mdx
Labels: Design review OK, Func Review OK, :rocket: Ready to Merge, Tech review OK, cross-team
