Repository 1024pix/pix-ui, pull requests merged in 2022-10, with the labels that each got.

#258 [FEATURE] Centre la PixModal en hauteur
  addon/styles/_pix-modal.scss
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, team-evaluation, cross-team

#259 [TECH] Mettre à jour la doc PixMultiSelect, pour la rendre plus lisible (PIX-5806)
  app/stories/pix-multi-select.stories.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, cross-team

#261 [BREAKING CHANGES][FEATURE] Suppression du padding dans le composant `PixBlock` (PIX-5971).
  addon/components/pix-background-header.hbs
  addon/styles/_pix-background-header.scss
  addon/styles/_pix-block.scss
  app/stories/pix-background-header.stories.js
  app/stories/pix-block.stories.mdx
  tests/integration/components/pix-background-header-test.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, team-evaluation, :warning: BREAKING CHANGES :warning:

#241 [FEATURE] PixCollapsible : Autoriser l'utilisation d'un Block Content pour le titre
  addon/components/pix-collapsible.hbs
  addon/styles/_pix-collapsible.scss
  app/stories/pix-collapsible.stories.js
  app/stories/pix-collapsible.stories.mdx
Labels: :rocket: Ready to Merge, cross-team, team-contenu

#263 [BUGFIX] Permettre le scroll quand la modale est détruite
  app/modifiers/trap-focus.js
Labels: :rocket: Ready to Merge, team-evaluation

#267 [FEATURE] Gérer l'échappement de la tooltip (PIX-6114)
  addon/components/pix-tooltip.hbs
  addon/components/pix-tooltip.js
  addon/styles/_pix-tooltip.scss
  tests/integration/components/pix-tooltip-test.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, team-evaluation

#268 [BUGFIX] Empêcher la propagation des événements dans tous les enfants sur la Tooltip (PIX-6149)
  addon/components/pix-tooltip.hbs
  addon/components/pix-tooltip.js
  addon/styles/_pix-tooltip.scss
  app/stories/pix-tooltip.stories.js
  app/stories/pix-tooltip.stories.mdx
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, team-evaluation
