Repository 1024pix/pix-ui, pull requests merged in 2023-10, with the labels that each got.

#484 [BUGFIX] Corrige les scénarios ember-try
  .circleci/config.yml
  config/ember-try.js
Labels: :rocket: Ready to Merge, Tech review OK, cross-team

#426 [TECH] add turboSnap
  package.json
Labels: :rocket: Ready to Merge, Tech review OK, cross-team

#479 [FEATURE] Retirer le Pix Dropdown de Storybook (PIX-9205)
  addon/components/pix-dropdown.hbs
  addon/components/pix-dropdown.js
  addon/styles/_pix-dropdown.scss
  addon/styles/addon.scss
  app/components/pix-dropdown.js
  app/stories/form.stories.js
  app/stories/pix-dropdown.mdx
  app/stories/pix-dropdown.stories.js
  tests/integration/components/pix-dropdown-test.js
Labels: :rocket: Ready to Merge, Tech review OK

#478 [DOCS] Tester des changements sur Pix UI en développement sur une app localement.
  docs/test-component-without-release.mdx
  docs/test-pix-ui-locally.mdx
Labels: :rocket: Ready to Merge, cross-team
