Repository 1024pix/pix-ui, pull requests merged in 2023-08, with the labels that each got.

#456 [FEATURE] Ajout des styles disabled et readonly du PixInput (PIX-8793).
  addon/styles/_pix-input.scss
  addon/styles/pix-design-tokens/_form.scss
  app/stories/pix-input.mdx
  app/stories/pix-input.stories.js
Labels: Design review OK, Func Review OK, :rocket: Ready to Merge, Tech review OK, cross-team

#423 [TECH] Mise à jour du changelog
  CHANGELOG.md
Labels: :rocket: Ready to Merge, cross-team

#458 [TECH] N'autorise qu'une seule version de storybook
  package-lock.json
  package.json
Labels: :rocket: Ready to Merge, Tech review OK, cross-team

#464 [TECH] Mise à jour du template de PR
  docs/pull_request_template.md
Labels: :rocket: Ready to Merge, Tech review OK, cross-team, no-review-app
