Repository 1024pix/pix-ui, pull requests merged in 2023-03, with the labels that each got.

#348 [BUGFIX] Rendre la ligne entière d'une option du multiselect cliquable (PIX-6957)
  addon/components/pix-checkbox.hbs
  addon/components/pix-multi-select.hbs
  addon/styles/_pix-checkbox.scss
  addon/styles/_pix-multi-select.scss
  app/stories/pix-checkbox.stories.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, team-prescription

#353 [BUGFIX] Améliorer l'accessibilité de PixStar (PIX-7349)
  addon/components/pix-stars.hbs
  tests/integration/components/pix-stars-test.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, cross-team

#355 [BUG] Corrige le PixCheckbox pour éviter de cacher l'input en utilisant la propriété screenReaderOnly
  addon/components/pix-checkbox.hbs
Labels: :rocket: Ready to Merge, Tech review OK, cross-team

#356 [TECH] Supprimer des fichiers inutiles (PIX-7402).
  app/components/pix-modal-content.js
  app/components/pix-modal-footer.js
Labels: :rocket: Ready to Merge, Tech review OK, cross-team

#357 [CHORE] Utiliser la propriété iconBefore dans le bouton du filterBanner (PIX-7415)
  addon/components/pix-button.hbs
  addon/components/pix-filter-banner.hbs
  app/stories/pix-button.stories.js
  tests/integration/components/pix-button-test.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, team-prescription

#360 [FEATURE] Vérifie la compatibilité avec embroider sur la ci
  .circleci/config.yml
  app/stories/pix-pagination.stories.mdx
  app/stories/pix-search-input.stories.mdx
  config/ember-try.js
  ember-cli-build.js
  package-lock.json
  package.json
Labels: :rocket: Ready to Merge, Tech review OK, cross-team

#361 [BUGFIX] Le contenu du `PixCollapsible` ne se rend plus en lazy
  addon/components/pix-collapsible.hbs
  addon/components/pix-collapsible.js
  tests/integration/components/pix-collapsible-test.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, cross-team

#350 [TECH] Aligne les noms des variables SCSS d'espacement et documente des Design Token (PIX-7523)
  addon/styles/_pix-banner.scss
  addon/styles/_pix-button.scss
  addon/styles/_pix-collapsible.scss
  addon/styles/_pix-dropdown.scss
  addon/styles/_pix-filter-banner.scss
  addon/styles/_pix-indicator-card.scss
  addon/styles/_pix-input-password.scss
  addon/styles/_pix-input.scss
  addon/styles/_pix-modal.scss
  addon/styles/_pix-multi-select.scss
  addon/styles/_pix-search-input.scss
  addon/styles/_pix-select.scss
  addon/styles/_pix-toggle.scss
  addon/styles/pix-design-tokens/_form.scss
  addon/styles/pix-design-tokens/_shadows.scss
  addon/styles/pix-design-tokens/_spacing.scss
  docs/shadow.stories.mdx
  docs/spacing.stories.mdx
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, cross-team

#367 [FEATURE] Mise à jour du Design Token "typographie" (PIX-7515)
  addon/styles/_pix-banner.scss
  addon/styles/_pix-button-base.scss
  addon/styles/_pix-checkbox.scss
  addon/styles/_pix-filter-banner.scss
  addon/styles/_pix-indicator-card.scss
  addon/styles/_pix-input-code.scss
  addon/styles/_pix-input.scss
  addon/styles/_pix-modal.scss
  addon/styles/_pix-multi-select.scss
  addon/styles/_pix-progress-gauge.scss
  addon/styles/_pix-radio-button.scss
  addon/styles/_pix-search-input.scss
  addon/styles/_pix-select.scss
  addon/styles/_pix-selectable-tag.scss
  addon/styles/_pix-sidebar.scss
  addon/styles/_pix-tag.scss
  addon/styles/_pix-textarea.scss
  addon/styles/_pix-toggle.scss
  addon/styles/_pix-tooltip.scss
  addon/styles/normalize-reset/_reset.scss
  addon/styles/pix-design-tokens/_fonts.scss
  addon/styles/pix-design-tokens/_form.scss
  addon/styles/pix-design-tokens/_typography.scss
  docs/design-tokens.stories.mdx
  docs/pix-design-tokens-dev.stories.mdx
  docs/typography.stories.mdx
  public/fonts/OpenSans/OpenSans-Light.ttf
  public/fonts/OpenSans/OpenSans-Medium.ttf
  public/fonts/OpenSans/OpenSans-Regular.ttf
  public/fonts/OpenSans/OpenSans-SemiBold.ttf
  public/fonts/Roboto/Roboto-Bold.ttf
  public/fonts/Roboto/Roboto-Light.ttf
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, cross-team

#369 [BUGFIX] Correction typographies composant Indicator Card
  addon/styles/_pix-indicator-card.scss
Labels: :rocket: Ready to Merge, Tech review OK, cross-team

#364 [TECH] Mise à jour de ember-click-outside
  package-lock.json
  package.json
Labels: :rocket: Ready to Merge, Tech review OK, cross-team

#362 [CLEANUP] Nettoie quelques dépendances et de la doc
  docs/make-a-release.stories.mdx
  package-lock.json
  package.json
  scripts/get-pull-requests-to-release-in-prod.js
  scripts/publish.sh
Labels: :rocket: Ready to Merge, Tech review OK, cross-team

#365 [BUGFIX] Corriger la sémantique et l'affichage du scroll sur la dropdown du PixSelect (PIX-7480)
  addon/components/pix-select.hbs
  addon/styles/_pix-indicator-card.scss
  addon/styles/_pix-select.scss
  addon/styles/normalize-reset/_normalize.scss
  addon/styles/normalize-reset/_reset.scss
Labels: :rocket: Ready to Merge, Tech review OK, cross-team

#372 [BUGFIX] Augmenter l'épaisseur du label de PixInput (PIX-7574).
  addon/styles/_pix-input.scss
  addon/styles/pix-design-tokens/_form.scss
Labels: Design review OK, :rocket: Ready to Merge, Tech review OK, cross-team

#373 [BUGFIX] Rendre les couleurs des tags cohérentes avec celles des maquettes (PIX-7582)
  addon/styles/_pix-tag.scss
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, team-prescription

#375 [TECH] Améliorer l'affichage des éléments en screen-reader-only ayant des sous élements (PIX-7623)
  addon/styles/_a11y.scss
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, cross-team
