Repository 1024pix/pix-ui, pull requests merged in 2023-07, with the labels that each got.

#429 [TECH] Débloque la CI le temps de comprendre ce qui se passe
  config/ember-try.js
Labels: :rocket: Ready to Merge, Tech review OK, cross-team

#428 [BREAKING] Montée de version de Node.js minimum à la v16.17.0
  package-lock.json
  package.json
Labels: :rocket: Ready to Merge, Tech review OK, cross-team, :warning: BREAKING CHANGES :warning:

#435 [BREAKING_CHANGES][BUGFIX] Ajuster la taille du bouton upload à son contenu.
  addon/styles/_pix-button-base.scss
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK

#383 [TECH] Ajouter la compatibilité avec node18
  .circleci/config.yml
  .github/workflows/deploy-storybook.yml
  .nvmrc
  package-lock.json
  package.json
Labels: :rocket: Ready to Merge, Tech review OK, cross-team

#451 [TECH] Ajustements des versions de Node et npm
  .circleci/config.yml
  .github/workflows/deploy-storybook.yml
  package-lock.json
  package.json
Labels: :rocket: Ready to Merge, Tech review OK, cross-team

#453 [TECH] Ajout de l'ordonnancement des propriétés CSS
  .stylelintrc.json
  addon/styles/_a11y.scss
  addon/styles/_pix-background-header.scss
  addon/styles/_pix-banner.scss
  addon/styles/_pix-button-base.scss
  addon/styles/_pix-button.scss
  addon/styles/_pix-checkbox.scss
  addon/styles/_pix-collapsible.scss
  addon/styles/_pix-dropdown.scss
  addon/styles/_pix-filter-banner.scss
  addon/styles/_pix-filterable-and-searchable-select.scss
  addon/styles/_pix-icon-button.scss
  addon/styles/_pix-indicator-card.scss
  addon/styles/_pix-input-code.scss
  addon/styles/_pix-input-password.scss
  addon/styles/_pix-input.scss
  addon/styles/_pix-message.scss
  addon/styles/_pix-modal.scss
  addon/styles/_pix-multi-select.scss
  addon/styles/_pix-pagination.scss
  addon/styles/_pix-progress-gauge.scss
  addon/styles/_pix-radio-button.scss
  addon/styles/_pix-return-to.scss
  addon/styles/_pix-search-input.scss
  addon/styles/_pix-select.scss
  addon/styles/_pix-selectable-tag.scss
  addon/styles/_pix-sidebar.scss
  addon/styles/_pix-tag.scss
  addon/styles/_pix-textarea.scss
  addon/styles/_pix-toggle.scss
  addon/styles/_pix-tooltip.scss
  addon/styles/normalize-reset/_normalize.scss
  addon/styles/normalize-reset/_reset.scss
  addon/styles/pix-design-tokens/_fonts.scss
  addon/styles/pix-design-tokens/_form.scss
  addon/styles/pix-design-tokens/_typography.scss
  package-lock.json
  package.json
Labels: :rocket: Ready to Merge, Tech review OK, cross-team

#452 [BUGFIX] Ajuster la taille du bouton upload.
  addon/components/pix-button-upload.js
  addon/styles/_pix-button-base.scss
  addon/styles/_pix-button-upload.scss
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, team-prescription, team-certif, cross-team

#455 [BUGFIX] Corrige la personnalisation du logo de storybook
  .storybook/logo.svg
  .storybook/manager.js
  .storybook/storybook-custom-theme.js
Labels: :rocket: Ready to Merge, Tech review OK, cross-team

#454 [TECH] Ajouter une erreur de lint si `render` ou `find` ne sont pas importés depuis `@1024pix/ember-testing-library`
  .eslintrc.js
  blueprints/pix-component/files/tests/integration/components/pix-__name__-test.js
  package-lock.json
  package.json
  tests/integration/components/pix-background-header-test.js
  tests/integration/components/pix-banner-test.js
  tests/integration/components/pix-block-test.js
  tests/integration/components/pix-button-link-test.js
  tests/integration/components/pix-button-test.js
  tests/integration/components/pix-button-upload-test.js
  tests/integration/components/pix-icon-button-test.js
  tests/integration/components/pix-input-code-test.js
  tests/integration/components/pix-message-test.js
  tests/integration/components/pix-modal-test.js
  tests/integration/components/pix-pagination-test.js
  tests/integration/components/pix-radio-button-test.js
  tests/integration/components/pix-return-to-test.js
  tests/integration/components/pix-selectable-tag-test.js
  tests/integration/components/pix-sidebar-test.js
  tests/integration/components/pix-tag-test.js
  tests/integration/components/pix-textarea-test.js
  tests/integration/modifiers/on-escape-action-test.js
Labels: :rocket: Ready to Merge, Tech review OK, cross-team
