Repository 1024pix/pix-ui, pull requests merged in 2023-05, with the labels that each got.

#394 [TECH] Rendre Chromatic non bloquant lors du run de la CI (PIX-7932)
  .circleci/config.yml
Labels: :rocket: Ready to Merge, Tech review OK, cross-team

#354 [TECH] Améliorer l'expérience de dev
  .storybook/main.js
  package.json
Labels: :rocket: Ready to Merge, Tech review OK, cross-team

#393 [FEATURE] Uniformiser PixRadioButton et PixCheckbox (PIX-7900)
  addon/components/pix-checkbox.hbs
  addon/components/pix-checkbox.js
  addon/components/pix-radio-button.hbs
  addon/components/pix-radio-button.js
  addon/styles/_pix-checkbox.scss
  addon/styles/_pix-radio-button.scss
  app/stories/pix-checkbox.stories.js
  app/stories/pix-checkbox.stories.mdx
  app/stories/pix-radio-button.stories.js
  app/stories/pix-radio-button.stories.mdx
  tests/integration/components/pix-checkbox-test.js
  tests/integration/components/pix-radio-button-test.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, cross-team

#397 [FEATURE] Améliorer le composant PixFilterbanner (PIX-7854)
  addon/components/pix-button.hbs
  addon/components/pix-button.js
  addon/components/pix-filter-banner.hbs
  addon/components/pix-filter-banner.js
  app/stories/pix-filter-banner.stories.js
  tests/integration/components/pix-filter-banner-test.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, cross-team

#401 [TECH] Suppression de l'utilitaire uniqueId (PIX-8003)
  addon/components/pix-modal.js
  addon/components/pix-sidebar.js
  addon/utils/unique-id.js
Labels: :rocket: Ready to Merge, Tech review OK, cross-team

#406 [FEATURE] Enlever l'obligation d'avoir un label ou un ariaLabel pour le PixInput (PIX-8126)
  addon/components/pix-input.js
  app/stories/pix-input.stories.js
  app/stories/pix-input.stories.mdx
  tests/integration/components/pix-input-test.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, team-evaluation, cross-team

#415 [FEATURE] Utiliser les éléments HTML native pour le TextArea (PIX-8200)
  addon/components/pix-textarea.hbs
  addon/components/pix-textarea.js
  docs/adr/0001-utiliser-les-balises-html-natives.md
  tests/integration/components/pix-textarea-test.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, team-evaluation, cross-team
