Repository 1024pix/pix-ui, pull requests merged in 2023-12, with the labels that each got.

#501 [TECH] Ajout d'un délai d'attente avant la prise de Snapshots Chromatic
  .storybook/preview.js
Labels: :rocket: Ready to Merge, Tech review OK, cross-team

#499 [FEATURE] Remise à jour des couleurs et des espacements (PIX-9998)
  .gitignore
  addon/components/pix-button-base.js
  addon/components/pix-progress-gauge.js
  addon/components/pix-return-to.hbs
  addon/styles/_pix-background-header.scss
  addon/styles/_pix-banner.scss
  addon/styles/_pix-block.scss
  addon/styles/_pix-button-base.scss
  addon/styles/_pix-button.scss
  addon/styles/_pix-checkbox.scss
  addon/styles/_pix-collapsible.scss
  addon/styles/_pix-filter-banner.scss
  addon/styles/_pix-filterable-and-searchable-select.scss
  addon/styles/_pix-icon-button.scss
  addon/styles/_pix-indicator-card.scss
  addon/styles/_pix-input-code.scss
  addon/styles/_pix-input-password.scss
  addon/styles/_pix-input.scss
  addon/styles/_pix-message.scss
  addon/styles/_pix-modal.scss
  addon/styles/_pix-multi-select.scss
  addon/styles/_pix-pagination.scss
  addon/styles/_pix-progress-gauge.scss
  addon/styles/_pix-radio-button.scss
  addon/styles/_pix-return-to.scss
  addon/styles/_pix-search-input.scss
  addon/styles/_pix-select.scss
  addon/styles/_pix-selectable-tag.scss
  addon/styles/_pix-sidebar.scss
  addon/styles/_pix-stars.scss
  addon/styles/_pix-tag.scss
  addon/styles/_pix-textarea.scss
  addon/styles/_pix-toggle.scss
  addon/styles/_pix-tooltip.scss
  addon/styles/pix-design-tokens/_colors.scss
  addon/styles/pix-design-tokens/_form.scss
  addon/styles/pix-design-tokens/_spacing.scss
  app/stories/pix-button.stories.js
  app/stories/pix-indicator-card.stories.js
  app/stories/pix-progress-gauge.mdx
  app/stories/pix-progress-gauge.stories.js
  app/stories/pix-return-to.stories.js
  app/stories/pix-stars.stories.js
  app/stories/pix-tag.stories.js
  docs/colors-palette.mdx
  docs/design-tokens.mdx
  docs/spacing.mdx
  package.json
  scripts/migrate-colors-scss-vars-to-css-vars.sh
  scripts/migrate-spacing-scss-vars-to-css-vars.sh
  tests/integration/components/pix-progress-gauge-test.js
  tests/integration/components/pix-tag-test.js
Labels: Design review OK, :rocket: Ready to Merge, cross-team

#508 [TECH] Ajouter les explications de migration des couleurs et espacements dans le changelog
  CHANGELOG.md
Labels: :rocket: Ready to Merge, Tech review OK, cross-team, no-review-app

#500 [TECH] Simplifier la procédure de test en local
  docs/test-pix-ui-locally.mdx
Labels: :rocket: Ready to Merge, Tech review OK, cross-team

#519 [BUGFIX] Corriger le soucis de hover sur le bouton de retour. (PIX-10553)
  addon/styles/_pix-return-to.scss
Labels: Design review OK, Func Review OK, :rocket: Ready to Merge, Tech review OK, cross-team
