Repository 1024pix/pix-ui, pull requests merged in 2023-01, with the labels that each got.

#314 [BREAKING_CHANGE] Ajouter un normalize/reset css dans Pix UI (pix-6723)
  addon/styles/_pix-banner.scss
  addon/styles/_pix-button-base.scss
  addon/styles/_pix-button-link.scss
  addon/styles/_pix-checkbox.scss
  addon/styles/_pix-collapsible.scss
  addon/styles/_pix-dropdown.scss
  addon/styles/_pix-icon-button.scss
  addon/styles/_pix-input-code.scss
  addon/styles/_pix-input-password.scss
  addon/styles/_pix-input.scss
  addon/styles/_pix-message.scss
  addon/styles/_pix-modal.scss
  addon/styles/_pix-return-to.scss
  addon/styles/_pix-selectable-tag.scss
  addon/styles/_pix-sidebar.scss
  addon/styles/_pix-stars.scss
  addon/styles/_pix-tag.scss
  addon/styles/_pix-textarea.scss
  addon/styles/_pix-tooltip.scss
  addon/styles/_reset-css.scss
  addon/styles/addon.scss
  addon/styles/normalize-reset/_normalize.scss
  addon/styles/normalize-reset/_reset.scss
  addon/styles/normalize-reset/index.scss
  addon/styles/pix-design-tokens/_breakpoints.scss
  addon/styles/pix-design-tokens/_colors.scss
  addon/styles/pix-design-tokens/_fonts.scss
  addon/styles/pix-design-tokens/_form.scss
  addon/styles/pix-design-tokens/_shadows.scss
  addon/styles/pix-design-tokens/_spacing.scss
  addon/styles/pix-design-tokens/_typography.scss
  addon/styles/pix-design-tokens/index.scss
  app/stories/pix-checkbox.stories.js
  app/stories/pix-multi-select.stories.js
  blueprints/pix-component/files/addon/styles/_pix-__name__.scss
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, cross-team

#317 [BUGFIX] La CI sort en erreur alors que les tests sont OK en local
  .circleci/config.yml
Labels: :rocket: Ready to Merge, Tech review OK, team-captains

#315 [BUGFIX] Améliorer le comportement du PixSelect (PIX-6775)
  addon/components/pix-select.hbs
  addon/components/pix-select.js
  addon/styles/_pix-select.scss
  app/stories/pix-select.stories.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, cross-team

#318 [TECH] Changement du ratio minimal pour la couleur de fond accessible de 4.5 à 3 (PIX-6802)
  addon/utils/accessible-contrasted-color-generator.js
  tests/unit/utils/accessible-contrasted-color-generator-test.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, team-prescription

#319 [FEATURE] Ajouter un argument IconPrefixe au composant IndicatorCard afin d'autoriser l'utilisation d'icônes personnalisées (PIX-6809)
  addon/components/pix-indicator-card.hbs
  app/stories/pix-indicator-card.stories.js
  app/stories/pix-indicator-card.stories.mdx
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, team-prescription

#321 [TECH] Stabilise le premier lancement de Storybook en dev
  package.json
Labels: :rocket: Ready to Merge, Tech review OK, cross-team

#320 [FEATURE] Déplacer le focus sur le champ lorsque le bouton pour masquer/afficher le mot de passe est cliqué sur PixInputPassword (PIX-6855)
  addon/components/pix-input-password.js
  addon/styles/_pix-input-password.scss
  addon/styles/_pix-input.scss
  tests/integration/components/pix-input-password-test.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, cross-team

#316 [FEATURE] Création d'un input permettant de chercher/filtrer (PIX-6780)
  addon/components/pix-search-input.hbs
  addon/components/pix-search-input.js
  addon/styles/_pix-search-input.scss
  addon/styles/addon.scss
  app/components/pix-search-input.js
  app/stories/pix-search-input.stories.js
  app/stories/pix-search-input.stories.mdx
  app/stories/pix-select.stories.mdx
  ember-cli-build.js
  package-lock.json
  package.json
  tests/integration/components/pix-search-input-test.js
  tests/unit/components/pix-search-input-test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-acces, cross-team

#325 [BUGFIX] Ajouter le paramètre permettant de ne pas afficher la valeur par défaut dans le fat composant (PIX-6925)
  addon/components/pix-filterable-and-searchable-select.hbs
  app/stories/pix-filterable-and-searchable-select.stories.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, team-prescription

#327 [TECH] Remplacer les valeurs d'`id` par du kebab case
  app/stories/pix-checkbox.stories.js
  app/stories/pix-input-password.stories.js
  app/stories/pix-input.stories.js
Labels: :rocket: Ready to Merge, Tech review OK, cross-team
