Repository 1024pix/pix-ui, pull requests merged in 2023-04, with the labels that each got.

#376 [FEATURE] Rendre PixStars adaptatif et plus accessible (PIX-7625).
  addon/components/pix-stars.hbs
  addon/components/pix-stars.js
  addon/styles/_pix-stars.scss
  addon/styles/pix-design-tokens/_colors.scss
  app/stories/pix-stars.stories.js
  app/stories/pix-stars.stories.mdx
  tests/integration/components/pix-stars-test.js
Labels: Design review OK, Func Review OK, :rocket: Ready to Merge, Tech review OK, team-evaluation

#377 [BUGFIX] Faire en sorte que la dropdown du select puisse s'ouvrir ailleurs qu'en bas si besoin (PIX-7237)
  addon/components/pix-select.hbs
  app/stories/pix-select.stories.js
  app/stories/pix-select.stories.mdx
  package-lock.json
  package.json
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, team-prescription, cross-team

#381 [TECH] Modification de la valeur du Design Token warning-60 et suppression des placeholders de font-weight (PIX-7666).
  addon/styles/pix-design-tokens/_colors.scss
  addon/styles/pix-design-tokens/_typography.scss
  docs/colors-palette.stories.mdx
  docs/typography.stories.mdx
Labels: :rocket: Ready to Merge, Tech review OK, cross-team

#384 [FEATURE] Ajouter une icône avant le label du composant Pix-Select (PIX-7634)
  addon/components/pix-select.hbs
  app/stories/pix-select.stories.js
  app/stories/pix-select.stories.mdx
  tests/integration/components/pix-select-test.js
Labels: :rocket: Ready to Merge, cross-team

#387 [FEATURE] Ne plus calculer le couleur de fond d'icône du PixIndicatorCard (PIX-7746)
  addon/components/pix-indicator-card.hbs
  addon/components/pix-indicator-card.js
  addon/styles/_pix-indicator-card.scss
  addon/utils/accessible-contrasted-color-generator.js
  app/stories/pix-indicator-card.stories.js
  package-lock.json
  package.json
  tests/unit/utils/accessible-contrasted-color-generator-test.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, team-prescription

#389 [FEATURE] Ajouter l'argument requiredLabel au TextArea (PIX-7710)
  addon/components/pix-textarea.hbs
  addon/components/pix-textarea.js
  app/stories/form.stories.js
  app/stories/pix-textarea.stories.js
  app/stories/pix-textarea.stories.mdx
  tests/integration/components/pix-textarea-test.js
  tests/unit/components/pix-textarea-test.js
Labels: :eyes: Func Review Needed, :rocket: Ready to Merge, :eyes: Tech Review Needed, cross-team

#390 [FEATURE] Ajouter Chromatic (PIX-7872)
  .circleci/config.yml
  .gitignore
  package-lock.json
  package.json
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, cross-team

#388 [FEATURE] Rectifier et uniformiser les composants Checkbox et Radio
  addon/components/pix-checkbox.hbs
  addon/components/pix-checkbox.js
  addon/components/pix-radio-button.hbs
  addon/styles/_pix-checkbox.scss
  addon/styles/_pix-radio-button.scss
  addon/styles/pix-design-tokens/_form.scss
  app/stories/pix-checkbox.stories.js
  app/stories/pix-checkbox.stories.mdx
  app/stories/pix-radio-button.stories.js
  app/stories/pix-radio-button.stories.mdx
  tests/integration/components/pix-checkbox-test.js
  tests/integration/components/pix-radio-button-test.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, cross-team

#391 [FEATURE] Améliorer la lisibilité des tags (PIX-7827)
  addon/styles/_pix-selectable-tag.scss
  addon/styles/_pix-tag.scss
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, team-prescription

#392 [BUGFIX] Éviter le rétrécissement des inputs checkbox et radio (PIX-7896).
  addon/styles/_pix-checkbox.scss
  addon/styles/_pix-radio-button.scss
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, cross-team
