Repository 1024pix/pix-ui, pull requests merged in 2023-06, with the labels that each got.

#417 [BREAKING] Met à jour la PixProgressBar avec le nouveau design (PIX-8172)
  addon/components/pix-progress-gauge.hbs
  addon/components/pix-progress-gauge.js
  addon/styles/_pix-progress-gauge.scss
  app/stories/pix-progress-gauge.stories.js
  app/stories/pix-progress-gauge.stories.mdx
  tests/integration/components/pix-progress-gauge-test.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, cross-team

#424 [BUGFIX] définir une largeur fixe pour le texte de pourcentage de PixProgressGauge (PIX-8439).
  addon/styles/_pix-progress-gauge.scss
Labels: Design review OK, :rocket: Ready to Merge, Tech review OK, team-evaluation

#425 [BUGFIX] Réduire la largeur minimum de PixProgressGauge (PIX-8457)
  addon/styles/_pix-progress-gauge.scss
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, team-evaluation, cross-team
