Repository 1024pix/pix-ui, pull requests merged in 2023-02, with the labels that each got.

#326 [FEATURE] utiliser une div comme tag parent de PixTooltip (PIX-6816)
  addon/components/pix-tooltip.hbs
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, team-evaluation

#330 [BUG] Ajouter une min-width au PixIconButton (PIX-7003)
  addon/styles/_pix-icon-button.scss
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, team-prescription

#329 [TECH] Améliorations techniques diverses
  app/stories/pix-banner.stories.js
  app/stories/pix-indicator-card.stories.js
  app/stories/pix-tooltip.stories.js
  app/stories/pix-tooltip.stories.mdx
Labels: :rocket: Ready to Merge, Tech review OK, cross-team

#328 [FEATURE] Ajout de l'état de succès pour les composants pixInput et pixInputPassword
  addon/components/pix-input-password.hbs
  addon/components/pix-input-password.js
  addon/components/pix-input.hbs
  addon/components/pix-input.js
  addon/styles/_pix-input-password.scss
  addon/styles/_pix-input.scss
  addon/styles/pix-design-tokens/_form.scss
  app/stories/form.stories.js
  app/stories/pix-input-password.stories.js
  app/stories/pix-input-password.stories.mdx
  app/stories/pix-input.stories.js
  app/stories/pix-input.stories.mdx
  tests/integration/components/pix-input-password-test.js
  tests/integration/components/pix-input-test.js
Labels: :rocket: Ready to Merge, cross-team

#332 [TECH] Monter la version de Node.js en 16.19.0
  .circleci/config.yml
  .github/workflows/deploy-storybook.yml
  .nvmrc
Labels: :rocket: Ready to Merge, Tech review OK, cross-team

#333 [TECH] Ajouter la configuration pour Renovate
  .github/renovate.json
Labels: :rocket: Ready to Merge, Tech review OK, cross-team

#337 [BUGFIX] utiliser la font-size du navigateur pour le calcul de la taille du PixSelect (PIX-7128)
  addon/components/pix-select.js
  addon/styles/_pix-select.scss
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, team-evaluation, cross-team

#340 [BUGFIX] Ne pas permettre le focus de l'option par défaut cachée du PixSelect (PIX-7196)
  addon/components/pix-select.hbs
  addon/components/pix-select.js
  tests/integration/components/pix-select-test.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, cross-team

#335 [TECH] Améliorations techniques diverses
  app/stories/pix-filterable-and-searchable-select.stories.js
  app/stories/pix-multi-select.stories.js
Labels: :rocket: Ready to Merge, Tech review OK, cross-team

#336 [TECH] Mise en place de Stylelint
  .circleci/config.yml
  .stylelintrc.json
  package-lock.json
  package.json
Labels: :rocket: Ready to Merge, Tech review OK, cross-team

#343 [TECH] Active la règle de lint SCSS d'indentation
  .stylelintrc.json
  addon/styles/_a11y.scss
  addon/styles/_pix-collapsible.scss
  addon/styles/_pix-modal.scss
  addon/styles/normalize-reset/_normalize.scss
  addon/styles/normalize-reset/_reset.scss
  addon/styles/pix-design-tokens/_breakpoints.scss
Labels: :rocket: Ready to Merge, Tech review OK, cross-team

#344 [TECH] Active la règle de lint SCSS de format de couleurs
  .stylelintrc.json
  addon/styles/pix-design-tokens/_colors.scss
Labels: :rocket: Ready to Merge, Tech review OK, cross-team

#346 [TECH] Active la règle de lint SCSS pour ne pas mettre d'unité derrière les `0`
  .stylelintrc.json
  addon/styles/_pix-banner.scss
  addon/styles/_pix-block.scss
  addon/styles/_pix-filterable-and-searchable-select.scss
  addon/styles/_pix-modal.scss
  addon/styles/_pix-multi-select.scss
  addon/styles/_pix-select.scss
  addon/styles/_pix-tooltip.scss
  addon/styles/pix-design-tokens/_form.scss
Labels: :rocket: Ready to Merge, cross-team, no-review-app

#345 [TECH] Active la règle de lint SCSS d'ajout d'espace après les `:`
  .stylelintrc.json
  addon/styles/normalize-reset/_reset.scss
Labels: :rocket: Ready to Merge, Tech review OK, cross-team, no-review-app

#338 [FEATURE] Permettre au PixButton d'avoir des icônes avant et après le label (PIX-3038)
  addon/components/pix-button.hbs
  addon/styles/_pix-button.scss
  app/stories/pix-button.stories.js
  app/stories/pix-button.stories.mdx
  tests/integration/components/pix-button-test.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, cross-team

#339 [FEATURE] Accorder le style du PixCollapsible au Design System (PIX-7164)
  addon/components/pix-collapsible.hbs
  addon/components/pix-collapsible.js
  addon/styles/_pix-collapsible.scss
  tests/integration/components/pix-collapsible-test.js
Labels: Design review OK, Func Review OK, :rocket: Ready to Merge, cross-team

#347 [TECH] Active des règles de lint SCSS d'espacement
  .stylelintrc.json
  addon/styles/_pix-banner.scss
  addon/styles/_pix-button.scss
  addon/styles/_pix-checkbox.scss
  addon/styles/_pix-dropdown.scss
  addon/styles/_pix-filterable-and-searchable-select.scss
  addon/styles/_pix-indicator-card.scss
  addon/styles/_pix-input-password.scss
  addon/styles/_pix-input.scss
  addon/styles/_pix-message.scss
  addon/styles/_pix-modal.scss
  addon/styles/_pix-multi-select.scss
  addon/styles/_pix-pagination.scss
  addon/styles/_pix-return-to.scss
  addon/styles/_pix-select.scss
  addon/styles/_pix-selectable-tag.scss
  addon/styles/_pix-sidebar.scss
  addon/styles/_pix-stars.scss
  addon/styles/_pix-tag.scss
  addon/styles/normalize-reset/_reset.scss
  addon/styles/pix-design-tokens/_breakpoints.scss
  addon/styles/pix-design-tokens/_colors.scss
  addon/styles/pix-design-tokens/_fonts.scss
  addon/styles/pix-design-tokens/_form.scss
  addon/styles/pix-design-tokens/_typography.scss
Labels: :rocket: Ready to Merge, Tech review OK, cross-team, no-review-app
