Repository 1024pix/pix-ui, pull requests merged in 2023-11, with the labels that each got.

#487 [TECH] Suppression du support Node 16 et Node 18
  .circleci/config.yml
  package-lock.json
  package.json
Labels: :rocket: Ready to Merge, Tech review OK, cross-team

#488 [TECH] Supprime un warning
  .storybook/main.js
  app/stories/pix-multi-select.mdx
  docs/design-system.mdx
  docs/make-a-release.mdx
  docs/shadow.mdx
  docs/spacing.mdx
  docs/storybook.mdx
  docs/typography.mdx
  docs/use-component.mdx
  package-lock.json
  package.json
Labels: :rocket: Ready to Merge, Tech review OK, cross-team

#494 [DOC] Ajout de la doc pour la classe `screen-reader-only` (pix-7740)
  docs/use-utility-classes.mdx
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, cross-team

#492 [TECH] Mise à jour de la classe .screen-reader-only
  addon/styles/_a11y.scss
Labels: :rocket: Ready to Merge, Tech review OK

#498 [CHORE] Améliorer le composant pix input code (Pix-9824)
  addon/components/pix-input-code.hbs
  addon/components/pix-input-code.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, 🎒👧🏽👦🏾 Pix1D

#497 [FEATURE] Remise à jour des typographies des titres (PIX-9969)
  addon/styles/pix-design-tokens/_fonts.scss
  addon/styles/pix-design-tokens/_typography.scss
  docs/pix-design-tokens-dev.mdx
  docs/typography.mdx
  public/fonts/Nunito/Nunito-Bold.ttf
Labels: Design review OK, :rocket: Ready to Merge, Tech review OK, cross-team
