Repository 1024pix/pix-ui, pull requests merged in 2024-01, with the labels that each got.

#515 [TECH] Retirer les attributs déprécié du PixButton (PIX-10483)
  addon/components/pix-button.hbs
  app/stories/pix-button-link.stories.js
  app/stories/pix-button.stories.js
  tests/integration/components/pix-button-test.js
Labels: :rocket: Ready to Merge, Tech review OK, cross-team, :warning: BREAKING CHANGES :warning:

#522 [BUGFIX] Ajouter la font-weight medium pour les Label des inputs (PIX-10622)
  addon/styles/_pix-checkbox.scss
  addon/styles/_pix-radio-button.scss
  addon/styles/component-state/_form.scss
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, cross-team

#523 [BUGFIX] Mauvaise affichage des boutons / input avec un aria-diasbled false (PIX-10629)
  addon/styles/_pix-button-base.scss
  addon/styles/component-state/_form.scss
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, cross-team

#524 [BUGFIX] Harmoniser la taille des boutons (PIX-10623).
  addon/components/pix-button-link.js
  addon/styles/_pix-button-base.scss
  addon/styles/component-state/_form.scss
  app/stories/form.mdx
  app/stories/form.stories.js
Labels: :rocket: Ready to Merge, cross-team

#525 [BUGFIX] Harmoniser la taille du PixButtonUpload avec les autres boutons (PIX-10669).
  addon/styles/_pix-button-base.scss
  app/stories/form.stories.js
Labels: :rocket: Ready to Merge, cross-team
