Repository 1024pix/pix-ui, pull requests merged in 2024-02, with the labels that each got.

#514 [FEATURE] Ajouter un nouveau composant PixLabel (PIX-10453)
  addon/components/pix-checkbox.hbs
  addon/components/pix-checkbox.js
  addon/components/pix-filterable-and-searchable-select.hbs
  addon/components/pix-filterable-and-searchable-select.js
  addon/components/pix-input-password.hbs
  addon/components/pix-input.hbs
  addon/components/pix-input.js
  addon/components/pix-label.hbs
  addon/components/pix-label.js
  addon/components/pix-multi-select.hbs
  addon/components/pix-radio-button.hbs
  addon/components/pix-search-input.hbs
  addon/components/pix-select.hbs
  addon/components/pix-select.js
  addon/components/pix-textarea.hbs
  addon/components/pix-textarea.js
  addon/components/pix-toggle.hbs
  addon/components/pix-toggle.js
  addon/styles/_pix-checkbox.scss
  addon/styles/_pix-filterable-and-searchable-select.scss
  addon/styles/_pix-input-code.scss
  addon/styles/_pix-input-password.scss
  addon/styles/_pix-input.scss
  addon/styles/_pix-label.scss
  addon/styles/_pix-multi-select.scss
  addon/styles/_pix-radio-button.scss
  addon/styles/_pix-search-input.scss
  addon/styles/_pix-select.scss
  addon/styles/_pix-textarea.scss
  addon/styles/_pix-toggle.scss
  addon/styles/addon.scss
  addon/styles/component-state/_form.scss
  addon/styles/pix-design-tokens/_typography.scss
  app/components/pix-label.js
  app/stories/pix-checkbox.mdx
  app/stories/pix-checkbox.stories.js
  app/stories/pix-filterable-and-searchable-select.stories.js
  app/stories/pix-input-password.mdx
  app/stories/pix-input-password.stories.js
  app/stories/pix-input.mdx
  app/stories/pix-input.stories.js
  app/stories/pix-label.mdx
  app/stories/pix-label.stories.js
  app/stories/pix-multi-select.stories.js
  app/stories/pix-radio-button.stories.js
  app/stories/pix-search-input.mdx
  app/stories/pix-search-input.stories.js
  app/stories/pix-select.stories.js
  app/stories/pix-textarea.stories.js
  app/stories/pix-toggle.stories.js
  config/icons.js
  tests/integration/components/pix-checkbox-test.js
  tests/integration/components/pix-input-password-test.js
  tests/integration/components/pix-label-test.js
  tests/integration/components/pix-search-input-test.js
  tests/integration/components/pix-select-test.js
  tests/integration/components/pix-textarea-test.js
  tests/unit/components/pix-select-test.js
  tests/unit/components/pix-textarea-test.js
Labels: Design review OK, :rocket: Ready to Merge, Tech review OK, cross-team, :warning: BREAKING CHANGES :warning:

#541 [TECH] Utiliser le padding au lieu de définir une height pour les composant select
  addon/styles/_pix-multi-select.scss
  addon/styles/_pix-select.scss
Labels: :rocket: Ready to Merge, Tech review OK, cross-team

#543 [TECH] Retirer les propriété déprécié des Pix Button (PIX-11291)
  addon/styles/_pix-button-base.scss
  app/stories/pix-button-upload.stories.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, team-prescription, cross-team

#539 [TECH] Proposer un nouveau workflow de déploiement continue.
  .github/workflows/npm-publish.yml
  .github/workflows/release.yml
Labels: :rocket: Ready to Merge

#548 [TECH] Donner les droits à l'action `release` de pusher sur dev
  .github/workflows/release.yml
Labels: :rocket: Ready to Merge

#549 [TECH] Utiliser le bon token GitHub pour l'action `release`
  .github/workflows/release.yml
Labels: :rocket: Ready to Merge

#553 [TECH] Prévenir les mauvais titre de PR.
  .github/workflows/check-pr-title.yaml
Labels: :rocket: Ready to Merge, Tech review OK, cross-team
