Repository 1024pix/pix-ui, pull requests merged in 2024-12, with the labels that each got.

#777 [FEATURE] Ajouter les icones de monitoring
  addon/helpers/icons.js
  public/svg/pix-sprite.svg
  svgs/icons/monitoring-fill_false.svg
Labels: Func Review OK, :rocket: Ready to Merge, cross-team

#771 [FEATURE] Création du composant Table (PIX-14514)
  addon/components/pix-table-column.hbs
  addon/components/pix-table-column.js
  addon/components/pix-table.hbs
  addon/components/pix-table.js
  addon/styles/_pix-table.scss
  addon/styles/addon.scss
  app/components/pix-table-column.js
  app/components/pix-table.js
  app/stories/pix-table-column.mdx
  app/stories/pix-table-column.stories.js
  app/stories/pix-table.mdx
  app/stories/pix-table.stories.js
  tests/integration/components/pix-table-test.js
Labels: Design review OK, Func Review OK, :rocket: Ready to Merge, Tech review OK, cross-team, team-contenu

#778 [BUGFIX] Retirer la couleur par défaut de la tooltip
  addon/styles/_pix-tooltip.scss
Labels: :rocket: Ready to Merge, Tech review OK, cross-team

#779 [FEATURE] Ajouter un composant colonne basique (PIX-14507)
  addon/components/pix-table-basic-column.hbs
  addon/components/pix-table-basic-column.js
  addon/styles/_pix-table-basic-column.scss
  addon/styles/_pix-table.scss
  app/components/pix-table-basic-column.js
  app/stories/pix-table-basic-column.mdx
  app/stories/pix-table-basic-column.stories.js
  tests/integration/components/pix-table-basic-column-test.js
Labels: Design review OK, Func Review OK, :rocket: Ready to Merge, Tech review OK, cross-team, team-contenu

#782 [BREAKING] Renommer les yields on/off du Pix Toggle Button (PIX-12700).
  addon/components/pix-toggle-button.hbs
  addon/styles/_pix-toggle-button.scss
  app/stories/pix-toggle-button.mdx
  app/stories/pix-toggle-button.stories.js
  tests/integration/components/pix-toggle-button-test.js
Labels: Design review OK, :rocket: Ready to Merge

#781 [FEATURE] Modifier les couleurs du PixReturnTo en cas de shade blanc (PIX-11642).
  addon/components/pix-return-to.js
  addon/styles/_pix-return-to.scss
  app/stories/pix-return-to.stories.js
  tests/integration/components/pix-return-to-test.js
  tests/unit/components/pix-return-to-test.js
Labels: Design review OK, :rocket: Ready to Merge

#784 [TECH] Suppression de le documentation concernant le type alert dépréciée sur Pix Notification Alert.
  app/stories/pix-notification-alert.mdx
Labels: :rocket: Ready to Merge, no-review-app

#786 [BREAKING] Migrer les variants communications de PixBannerAlert dans PixNotificationAlert (PIX-15547)
  addon/components/pix-notification-alert.js
  addon/styles/_pix-banner-alert.scss
  addon/styles/_pix-notification-alert.scss
  app/stories/pix-banner-alert.mdx
  app/stories/pix-banner-alert.stories.js
  app/stories/pix-notification-alert.mdx
  app/stories/pix-notification-alert.stories.js
  tests/integration/components/pix-banner-alert-test.js
  tests/integration/components/pix-notification-alert-test.js
Labels: Design review OK, Func Review OK, :rocket: Ready to Merge, Tech review OK, cross-team

#780 [FEATURE] Ajout d'icône manquante (PIX-15678)
  addon/helpers/icons.js
  public/svg/pix-sprite.svg
  svgs/icons/cogsMagic-fill_false.svg
  svgs/icons/cogsMagic-fill_true.svg
  svgs/icons/filter-fill_false.svg
  svgs/icons/filter-fill_true.svg
  svgs/icons/login-fill_true.svg
  svgs/icons/logout-fill_true.svg
  svgs/icons/mountain-fill_false.svg
  svgs/icons/mountain-fill_true.svg
  svgs/icons/tabletOff-fill_false.svg
  svgs/icons/tabletOff-fill_true.svg
  svgs/icons/think-fill_false.svg
  svgs/icons/think-fill_true.svg
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, cross-team

#785 [FEATURE] Rendre le MultiSelect avec recherche intégralement cliquable (PIX-15635).
  addon/components/pix-multi-select.hbs
  addon/components/pix-multi-select.js
  addon/styles/_pix-multi-select.scss
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, cross-team

#789 [FEATURE] Simplifier l'usage de pix-table (PIX-15682).
  addon/components/pix-table-basic-column.hbs
  addon/components/pix-table-basic-column.js
  addon/components/pix-table-column.hbs
  addon/components/pix-table-column.js
  addon/styles/_pix-table-column.scss
  addon/styles/_pix-table.scss
  app/components/pix-table-basic-column.js
  app/stories/pix-table-basic-column.mdx
  app/stories/pix-table-basic-column.stories.js
  app/stories/pix-table-column.mdx
  app/stories/pix-table-column.stories.js
  app/stories/pix-table.mdx
  app/stories/pix-table.stories.js
  tests/integration/components/pix-table-column-test.js
Labels: Design review OK, Func Review OK, :rocket: Ready to Merge, Tech review OK, cross-team, team-contenu

#783 [FEATURE] Permettre de trier les données de `PixTable` (PIX-15560)
  addon/components/pix-table-column.hbs
  addon/components/pix-table-column.js
  addon/styles/_pix-table.scss
  app/stories/pix-table-column.mdx
  app/stories/pix-table-column.stories.js
  app/stories/pix-table.stories.js
  tests/dummy/app/controllers/table-page.js
  tests/dummy/app/router.js
  tests/dummy/app/templates/application.hbs
  tests/dummy/app/templates/table-page.hbs
  tests/integration/components/pix-table-test.js
Labels: Design review OK, Func Review OK, :rocket: Ready to Merge, Tech review OK, cross-team, :warning: PR Inheritance, team-contenu

#788 [FEATURE] améliore l'affichage de PixStructureSwitcher (pix-15674)
  addon/styles/_pix-structure-switcher.scss
  tests/dummy/app/controllers/application.js
Labels: Design review OK, Func Review OK, :rocket: Ready to Merge, Tech review OK

#790 [FEATURE] Ajout des icônes stopwatch et barsUp (PIX-15723)
  addon/helpers/icons.js
  public/svg/pix-sprite.svg
  svgs/icons/barsUp-fill_false.svg
  svgs/icons/stopwatch-fill_false.svg
  svgs/icons/stopwatch-fill_true.svg
Labels: Design review OK, :rocket: Ready to Merge, Tech review OK, team-devcomp

#787 [BREAKING]: Utilisation de yield nommés dans le PixAppLayout (pix-15665)
  addon/components/pix-app-layout.hbs
  addon/styles/_pix-app-layout.scss
  app/stories/pix-app-layout.mdx
  app/stories/pix-app-layout.stories.js
  app/stories/pix-navigation.mdx
  tests/dummy/app/templates/application.hbs
  tests/integration/components/pix-app-layout-test.js
Labels: Design review OK, Func Review OK, :rocket: Ready to Merge, Tech review OK

#791 Revert "[BREAKING] Utilisation de yield nommés dans le PixAppLayout (pix-15665)"
  addon/components/pix-app-layout.hbs
  addon/styles/_pix-app-layout.scss
  app/stories/pix-app-layout.mdx
  app/stories/pix-app-layout.stories.js
  app/stories/pix-navigation.mdx
  tests/dummy/app/templates/application.hbs
  tests/integration/components/pix-app-layout-test.js
Labels: :rocket: Ready to Merge, Tech review OK

#794 [BUGFIX] Modification de l'état defaut du PixButton Tertiary (PIX-15732)
  addon/styles/_pix-button-base.scss
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, team-prescription

#793 [BUGFIX] removed z-index on inputs that have searchable = true [PIX-15763]
  addon/styles/_pix-multi-select.scss
Labels: :rocket: Ready to Merge, Tech review OK

#795 [TECH] Supprimer l'auto-merge local
  .github/workflows/auto-merge.yml
Labels: :rocket: Ready to Merge

#797 [TECH] Ajout de l'icône "Open in full"
  addon/helpers/icons.js
  public/svg/pix-sprite.svg
  svgs/icons/openInFull-fill_false.svg
Labels: :rocket: Ready to Merge, Tech review OK
