Repository 1024pix/pix-ui, pull requests merged in 2024-09, with the labels that each got.

#730 [TECH] Ne plus embarquer les .mdx / stories.js (PIX-14450)
  package.json
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, team-prescription, cross-team

#733 Revert "[BUMP] Update dependency ember-resolver to v13 (dossier racine)"
  package-lock.json
  package.json
Labels: :rocket: Ready to Merge, Tech review OK

#735 [BUGFIX] Corriger le chemin du sprite.svg (PIX-14493)
  addon/components/pix-icon.hbs
Labels: :rocket: Ready to Merge, Tech review OK, cross-team
