Repository 1024pix/pix-ui, pull requests merged in 2024-10, with the labels that each got.

#736 [FEATURE] Ajouter des icônes au composant PixIcon
  addon/helpers/icons.js
  public/svg/pix-sprite.svg
  svgs/icons/cloud_upload_24dp_E8EAED_FILL0_wght500_GRAD0_opsz24.svg
  svgs/icons/cloud_upload_24dp_E8EAED_FILL1_wght500_GRAD0_opsz24.svg
  svgs/icons/logout_24dp_E8EAED_FILL0_wght500_GRAD0_opsz24.svg
  svgs/icons/notifications_24dp_E8EAED_FILL0_wght500_GRAD0_opsz24.svg
  svgs/icons/notifications_24dp_E8EAED_FILL1_wght500_GRAD0_opsz24.svg
  svgs/icons/schedule_24dp_E8EAED_FILL0_wght500_GRAD0_opsz24.svg
  svgs/icons/schedule_24dp_E8EAED_FILL1_wght500_GRAD0_opsz24.svg
  svgs/icons/upload_file_24dp_E8EAED_FILL0_wght500_GRAD0_opsz24.svg
  svgs/icons/upload_file_24dp_E8EAED_FILL1_wght500_GRAD0_opsz24.svg
Labels: Design review OK, Func Review OK, :rocket: Ready to Merge, Tech review OK, cross-team

#739 [TECH] Ajout de l'icone calendar (PIX-14734)
  addon/helpers/icons.js
  public/svg/pix-sprite.svg
  svgs/icons/today_24dp_E8EAED_FILL0_wght500_GRAD0_opsz24.svg
  svgs/icons/today_24dp_E8EAED_FILL1_wght500_GRAD0_opsz24.svg
  svgs/rename-icon-id-in-sprite.sh
  svgs/svgo.config.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, cross-team

#742 [DOC] Réparer le lien dans le README qui mène vers la documentation pour la création d'un nouveau composant
  README.md
Labels: Func Review OK, :rocket: Ready to Merge, cross-team

#743 [BUGFIX] Le focus de Pix Select ne fonctionne pas dans tous les cas (PIX-14876)
  addon/components/pix-select.js
  tests/integration/components/pix-select-test.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, cross-team

#741 [FEATURE] Ajout d'icône manquante pour les différentes APP (PIX-14875)
  addon/helpers/icons.js
  public/svg/pix-sprite.svg
  svgs/icons/book_2_24dp_E8EAED_FILL0_wght500_GRAD0_opsz24.svg
  svgs/icons/book_2_24dp_E8EAED_FILL1_wght500_GRAD0_opsz24.svg
  svgs/icons/chat_24dp_E8EAED_FILL0_wght500_GRAD0_opsz24.svg
  svgs/icons/chat_24dp_E8EAED_FILL1_wght500_GRAD0_opsz24.svg
  svgs/icons/confirmation_number_24dp_E8EAED_FILL0_wght500_GRAD0_opsz24.svg
  svgs/icons/confirmation_number_24dp_E8EAED_FILL1_wght500_GRAD0_opsz24.svg
  svgs/icons/desktop_access_disabled_24dp_E8EAED_FILL0_wght500_GRAD0_opsz24.svg
  svgs/icons/desktop_access_disabled_24dp_E8EAED_FILL1_wght500_GRAD0_opsz24.svg
  svgs/icons/done_all_24dp_E8EAED_FILL0_wght500_GRAD0_opsz24.svg
  svgs/icons/mobile_off_24dp_E8EAED_FILL0_wght500_GRAD0_opsz24.svg
  svgs/icons/mobile_off_24dp_E8EAED_FILL1_wght500_GRAD0_opsz24.svg
  svgs/icons/move_to_inbox_24dp_E8EAED_FILL0_wght400_GRAD0_opsz24.svg
  svgs/icons/move_to_inbox_24dp_E8EAED_FILL1_wght400_GRAD0_opsz24.svg
  svgs/icons/percent_24dp_E8EAED_FILL0_wght500_GRAD0_opsz24.svg
  svgs/icons/person_add_24dp_E8EAED_FILL0_wght500_GRAD0_opsz24.svg
  svgs/icons/person_add_24dp_E8EAED_FILL1_wght500_GRAD0_opsz24.svg
  svgs/icons/speed_24dp_E8EAED_FILL0_wght500_GRAD0_opsz24.svg
  svgs/icons/speed_24dp_E8EAED_FILL1_wght500_GRAD0_opsz24.svg
  svgs/icons/trending_down_24dp_E8EAED_FILL0_wght500_GRAD0_opsz24.svg
  svgs/icons/trending_flat_24dp_E8EAED_FILL0_wght500_GRAD0_opsz24.svg
  svgs/icons/trending_up_24dp_E8EAED_FILL0_wght500_GRAD0_opsz24.svg
Labels: Design review OK, :rocket: Ready to Merge, cross-team
