Repository 1024pix/pix-ui, pull requests merged in 2024-07, with the labels that each got.

#693 [BUGFIX] retarde l'appel à hideTootltip
  addon/components/pix-tooltip.js
  tests/dummy/app/controllers/tooltip-page.js
  tests/dummy/app/templates/tooltip-page.hbs
Labels: :rocket: Ready to Merge

#692 [FEATURE] Supprimer l'option compact du composant PixTag (PIX-11127).
  addon/components/pix-collapsible.hbs
  addon/components/pix-tag.js
  addon/styles/_pix-tag.scss
  app/stories/pix-tag.mdx
  app/stories/pix-tag.stories.js
  tests/integration/components/pix-tag-test.js
Labels: :rocket: Ready to Merge, cross-team

#699 [TECH] Ajoute le support node@v22
  package-lock.json
  package.json
Labels: :rocket: Ready to Merge, Tech review OK, cross-team

#707 [TECH] Corriger les alertes SASS
  addon/styles/_pix-label-wrapped.scss
  addon/styles/_pix-selectable-tag.scss
Labels: :rocket: Ready to Merge, cross-team

#706 [BUGFIX] Corrige le scroll involontaire dans une page avec plusieurs modales (PIX-13529)
  app/modifiers/trap-focus.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, team-devcomp
