Repository 1024pix/pix-ui, pull requests merged in 2024-06, with the labels that each got.

#660 [BUGFIX] Aligner à gauche la liste des options des selects (PIX-12803).
  addon/components/pix-multi-select.hbs
  addon/components/pix-select.hbs
  app/stories/pix-multi-select.stories.js
  app/stories/pix-select.stories.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, cross-team

#664 [FEATURE] Ajouter un variant tile au composant PixRadioButton (PIX-12828)
  addon/components/pix-radio-button.hbs
  app/stories/pix-radio-button.mdx
  app/stories/pix-radio-button.stories.js
Labels: :rocket: Ready to Merge, cross-team, team-devcomp

#665 [TECH] Améliorer la docs des `Checkbox` et `RadioButton`
  app/stories/pix-checkbox-variant-tile.mdx
  app/stories/pix-checkbox-variant-tile.stories.js
  app/stories/pix-checkbox.mdx
  app/stories/pix-checkbox.stories.js
  app/stories/pix-radio-button-variant-tile.mdx
  app/stories/pix-radio-button-variant-tile.stories.js
  app/stories/pix-radio-button.mdx
  app/stories/pix-radio-button.stories.js
Labels: :rocket: Ready to Merge, cross-team

#674 [BUGFIX] Ajoute des icônes manquantes `magnifying-glass` et `arrow-left`
  app/stories/pix-button.stories.js
  app/stories/pix-icon-button.mdx
  app/stories/pix-toggle.stories.js
  config/icons.js
Labels: :rocket: Ready to Merge, cross-team

#669 [FEATURE] Ajouter des états succès/erreur au Checkbox `tile` (PIX-12834)
  addon/components/pix-checkbox.hbs
  addon/components/pix-checkbox.js
  addon/components/pix-label-wrapped.hbs
  addon/components/pix-label-wrapped.js
  addon/styles/_pix-checkbox.scss
  addon/styles/_pix-label-wrapped.scss
  addon/translations/fr.js
  app/stories/pix-checkbox-variant-tile.mdx
  app/stories/pix-checkbox-variant-tile.stories.js
  app/stories/pix-checkbox.stories.js
  config/icons.js
  tests/integration/components/pix-checkbox-test.js
Labels: :rocket: Ready to Merge, cross-team, team-devcomp

#678 [BUGFIX] Réparer la largeur du Select (PIX-12845).
  addon/components/pix-select.js
  addon/styles/_pix-select.scss
  tests/dummy/app/controllers/select-page.js
  tests/dummy/app/router.js
  tests/dummy/app/templates/select-page.hbs
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, cross-team

#673 [TECH] Gérer l'apparition du tooltip en CSS (PIX-12955).
  addon/components/pix-tooltip.hbs
  addon/components/pix-tooltip.js
  addon/styles/_pix-tooltip.scss
  app/stories/pix-tooltip.mdx
  app/stories/pix-tooltip.stories.js
  tests/dummy/app/controllers/tooltip-page.js
  tests/dummy/app/router.js
  tests/dummy/app/templates/tooltip-page.hbs
  tests/integration/components/pix-tooltip-test.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, cross-team

#681 [BUGFIX] Retirer le padding gauche / droite du bouton tertiaire (PIX-13037)
  addon/styles/_pix-button-base.scss
Labels: Design review OK, :rocket: Ready to Merge, team-prescription, cross-team

#679 [FEATURE] Ajouter des états succès/erreur au RadioButton tile (PIX-12836)
  addon/components/pix-radio-button.hbs
  addon/components/pix-radio-button.js
  addon/styles/_pix-radio-button.scss
  app/stories/pix-checkbox-variant-tile.mdx
  app/stories/pix-radio-button-variant-tile.mdx
  app/stories/pix-radio-button-variant-tile.stories.js
  tests/integration/components/pix-radio-button-test.js
  tests/unit/components/pix-radio-button-test.js
Labels: :rocket: Ready to Merge, cross-team, team-devcomp
