Repository 1024pix/pix-ui, pull requests merged in 2024-04, with the labels that each got.

#602 [BUMP] Revert "Update dependency node to v20.12.1"
  .circleci/config.yml
  .nvmrc
  package-lock.json
  package.json
Labels: :rocket: Ready to Merge, dependencies

#604 [TECH] Vérifier que la version de nodeJs soit disponible sur scalingo
  .github/workflows/check-node-version-availability-on-scalingo.yml
Labels: :rocket: Ready to Merge, cross-team

#582 [DOCS] Remise à jour de la doc de typographies
  docs/typography.mdx
Labels: Design review OK, :rocket: Ready to Merge, Tech review OK, cross-team

#608 [FEATURE] Permettre d'ajouter une composante d'opacité sur les couleurs (PIX-10838)
  addon/styles/pix-design-tokens/_colors.scss
Labels: :rocket: Ready to Merge, Tech review OK, cross-team
