Repository 1024pix/pix-ui, pull requests merged in 2024-05, with the labels that each got.

#618 [TECH] Avoir une CI déterministe
  .circleci/config.yml
Labels: :rocket: Ready to Merge, Tech review OK, cross-team

#617 [FEATURE] Gérer l'abscence de label pour les inputs et textarea
  addon/components/pix-input.hbs
  addon/components/pix-textarea.hbs
  app/stories/pix-input.mdx
  app/stories/pix-input.stories.js
  app/stories/pix-textarea.mdx
  app/stories/pix-textarea.stories.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, cross-team

#623 [TECH] Supprime des dépendances inutilisées
  package-lock.json
  package.json
Labels: cross-team

#621 [TECH] Màj GHA check titre PR pour utiliser Pix Actions
  .github/workflows/check-pr-title.yaml
Labels: :eyes: Tech Review Needed, cross-team

#625 [DOCS] Revues diverse
  app/stories/pix-checkbox.mdx
  app/stories/pix-checkbox.stories.js
  app/stories/pix-input-code.stories.js
  app/stories/pix-radio-button.mdx
  app/stories/pix-radio-button.stories.js
  app/stories/pix-search-input.stories.js
  app/stories/pix-select.stories.js
  app/stories/pix-sidebar.stories.js
  app/stories/pix-toggle.stories.js
  blueprints/pix-component/files/app/stories/pix-__name__.stories.js
Labels: cross-team

#624 [FEATURE] Modifier l'aspect du bouton transparent light (PIX-12416)
  addon/styles/_pix-button-base.scss
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, team-prescription, cross-team

#607 [BUGFIX] Permet le clique entre les input `radio` ou `checkbox` et leur label
  addon/components/pix-checkbox.hbs
  addon/components/pix-label.js
  addon/components/pix-radio-button.hbs
  addon/styles/_pix-checkbox.scss
  addon/styles/_pix-label.scss
  addon/styles/_pix-radio-button.scss
  app/stories/pix-label.stories.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, cross-team

#626 [FEATURE] Améliorations états `disabled` des champs de formulaire
  addon/components/pix-checkbox.hbs
  addon/components/pix-checkbox.js
  addon/components/pix-radio-button.hbs
  addon/components/pix-radio-button.js
  addon/styles/_pix-checkbox.scss
  addon/styles/_pix-label.scss
  addon/styles/_pix-radio-button.scss
  addon/styles/component-state/_form.scss
  tests/integration/components/pix-checkbox-test.js
  tests/integration/components/pix-radio-button-test.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, cross-team

#632 [BUGFIX] Corriger l'affichage des Checkbox/radioButton dans le cas du screen reader only
  addon/components/pix-checkbox.hbs
  addon/components/pix-label.hbs
  addon/components/pix-label.js
  addon/components/pix-radio-button.hbs
  app/stories/pix-checkbox.stories.js
  app/stories/pix-radio-button.stories.js
Labels: :rocket: Ready to Merge, cross-team

#642 [FEATURE] Mise à jour des tailles des boutons (PIX-12418)
  addon/styles/_pix-button-base.scss
  addon/styles/pix-design-tokens/_typography.scss
Labels: Design review OK, :rocket: Ready to Merge, Tech review OK, team-prescription, cross-team

#648 [FEATURE] Rendre la taille des boutons à small par défaut.
  addon/components/pix-button-base.js
  app/stories/pix-button-link.stories.js
  app/stories/pix-button-upload.stories.js
  app/stories/pix-button.mdx
  app/stories/pix-button.stories.js
  app/stories/pix-icon-button.mdx
  app/stories/pix-icon-button.stories.js
Labels: :rocket: Ready to Merge, cross-team

#650 [FEATURE] Modifier le Design du bouton tertiaire (PIX-12615)
  addon/styles/_pix-button-base.scss
Labels: Design review OK, Func Review OK, :rocket: Ready to Merge, Tech review OK, cross-team

#651 [TECH]: Aligner la hauteur de tous éléments boutons
  addon/styles/_pix-button-base.scss
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, cross-team

#657 [TECH] Nettoyage de Storybook
  .storybook/main.js
  .storybook/storybook-custom-theme.js
  package-lock.json
  package.json
Labels: :rocket: Ready to Merge, Tech review OK, cross-team

#656 [BUGFIX] `PixTextarea` prend tout l'espace à sa disposition (PIX-12468)
  addon/components/pix-textarea.hbs
  addon/styles/_pix-textarea.scss
  app/stories/pix-textarea.mdx
  app/stories/pix-textarea.stories.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, cross-team, team-devcomp

#655 [FEATURE] Ajout et usage d'une police Monospace
  addon/styles/_pix-input-code.scss
  addon/styles/_pix-input-password.scss
  addon/styles/pix-design-tokens/_fonts.scss
  addon/styles/pix-design-tokens/_typography.scss
  docs/typography.mdx
  public/fonts/RobotoMono/RobotoMono-Regular.woff2
Labels: Design review OK, Func Review OK, :rocket: Ready to Merge, Tech review OK, cross-team
