Repository 1024pix/pix-ui, pull requests merged in 2024-11, with the labels that each got.

#753 [BUGFIX] Ajouter des ariaHidden sur les PixIcon décorative (PIX-15154)
  addon/components/pix-banner.hbs
  addon/components/pix-button.hbs
  addon/components/pix-collapsible.hbs
  addon/components/pix-input-password.hbs
  addon/components/pix-input.hbs
  addon/components/pix-multi-select.hbs
  addon/components/pix-search-input.hbs
  addon/components/pix-select.hbs
  tests/integration/components/pix-select-test.js
Labels: :rocket: Ready to Merge, Tech review OK, team-prescription, cross-team

#750 [BUGFIX] Remplacer le alt par la balise title du svg (PIX-15105)
  addon/components/pix-icon.hbs
  addon/components/pix-icon.js
  app/stories/pix-icon.stories.js
  tests/integration/components/pix-icons-test.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, team-prescription, cross-team

#758 [FEATURE] Ajout de nouvelles icones (Pix-14991)
  addon/helpers/icons.js
  app/stories/pix-button.mdx
  app/stories/pix-button.stories.js
  docs/update-sprites.mdx
  public/svg/pix-sprite.svg
  svgs/icons/menu-fill_false.svg
  svgs/icons/sortAsc-fill_false.svg
  svgs/icons/sortAzAsc-fill_false.svg
  svgs/icons/sortAzDesc-fill_false.svg
  svgs/icons/sortDesc-fill_false.svg
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, team-prescription, cross-team

#755 [TECH] met à jour le dépendances storybook (pix-15222)
  .storybook/main.js
  .storybook/preview.js
  docs/typography.mdx
  package-lock.json
  package.json
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, dependencies

#482 [FEATURE] Créer le composant Pix Toast (PIX-9580).
  addon/components/pix-toast-container.hbs
  addon/components/pix-toast-container.js
  addon/components/pix-toast.hbs
  addon/components/pix-toast.js
  addon/components/toast-example.hbs
  addon/components/toast-example.js
  addon/services/pix-toast.js
  addon/styles/_pix-toast.scss
  addon/styles/_toast-example.scss
  addon/styles/addon.scss
  app/components/pix-toast-container.js
  app/components/pix-toast.js
  app/components/toast-example.js
  app/services/pix-toast.js
  app/stories/pix-toast.mdx
  app/stories/pix-toast.stories.js
  package.json
  tests/integration/components/pix-toast-container-test.js
  tests/integration/components/pix-toast-test.js
  tests/unit/services/pix-toast-test.js
Labels: Design review OK, :rocket: Ready to Merge, cross-team

#759 [FEATURE] Améliorer la barre de progression (PIX-15260)
  addon/components/pix-progress-gauge.hbs
  addon/components/pix-progress-gauge.js
  app/stories/pix-progress-gauge.mdx
  app/stories/pix-progress-gauge.stories.js
  tests/integration/components/pix-progress-gauge-test.js
Labels: :rocket: Ready to Merge, team-devcomp

#761 [BUGFIX] Corriger l'affichage des icônes sur les composants (PIX-15304)
  addon/styles/_pix-banner.scss
  addon/styles/_pix-button-base.scss
  addon/styles/_pix-collapsible.scss
  addon/styles/_pix-icon-button.scss
  addon/styles/_pix-indicator-card.scss
  addon/styles/_pix-input-password.scss
  addon/styles/_pix-label-wrapped.scss
  addon/styles/_pix-message.scss
  addon/styles/_pix-multi-select.scss
  addon/styles/_pix-select.scss
  addon/styles/_pix-toast.scss
  addon/styles/_pix-toggle.scss
  addon/styles/_pix-tooltip.scss
Labels: Design review OK, :rocket: Ready to Merge, Tech review OK, cross-team

#764 [FEATURE] Déplacer l'indicateur de requirement de PixLabel (PIX-15143).
  addon/components/pix-label.hbs
  tests/integration/components/pix-filterable-and-searchable-select-test.js
  tests/integration/components/pix-input-password-test.js
  tests/integration/components/pix-input-test.js
  tests/integration/components/pix-label-test.js
  tests/integration/components/pix-select-test.js
Labels: Design review OK, :rocket: Ready to Merge, Tech review OK, cross-team

#746 [BUGFIX] Éviter de `throw` si l'élément `aria-selected` de `PixSelect` n'existe plus ou pas encore (PIX-15018)
  addon/components/pix-select.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, cross-team

#766 [FEATURE] Mise à jour des border-radius sur la PixBanner (PIX-15403)
  addon/styles/_pix-banner.scss
Labels: Design review OK, :rocket: Ready to Merge, cross-team

#767 [TECH] Gestion de la transparence cross navigateur (PIX-15411)
  addon/styles/pix-design-tokens/_colors.scss
  docs/colors-palette.mdx
Labels: Design review OK, Func Review OK, :rocket: Ready to Merge, Tech review OK, cross-team

#757 [FEATURE] Ajouter le composant pour changer de structure (Pix-15220)
  addon/components/pix-app-layout.hbs
  addon/components/pix-app-layout.js
  addon/components/pix-navigation.hbs
  addon/components/pix-select-list.hbs
  addon/components/pix-select-list.js
  addon/components/pix-select.hbs
  addon/components/pix-select.js
  addon/components/pix-structure-switcher.hbs
  addon/components/pix-structure-switcher.js
  addon/styles/_pix-app-layout.scss
  addon/styles/_pix-navigation.scss
  addon/styles/_pix-select-list.scss
  addon/styles/_pix-select.scss
  addon/styles/_pix-structure-switcher.scss
  addon/styles/addon.scss
  app/components/pix-select-list.js
  app/components/pix-structure-switcher.js
  app/stories/pix-app-layout.mdx
  app/stories/pix-app-layout.stories.js
  app/stories/pix-navigation.mdx
  app/stories/pix-navigation.stories.js
  app/stories/pix-structure-switcher.mdx
  app/stories/pix-structure-switcher.stories.js
  package-lock.json
  package.json
  tests/dummy/app/controllers/application.js
  tests/dummy/app/controllers/select-page.js
  tests/dummy/app/templates/application.hbs
  tests/integration/components/pix-app-layout-test.js
  tests/integration/components/pix-select-test.js
  tests/integration/components/pix-structure-switcher-test.js
Labels: Design review OK, Func Review OK, :rocket: Ready to Merge, Tech review OK, cross-team

#769 [FEATURE] Mise à jour de l'icône tabletOff (PIX-15426)
  public/svg/pix-sprite.svg
  svgs/icons/tabletOff-fill_false.svg
  svgs/icons/tabletOff-fill_true.svg
Labels: Design review OK, :rocket: Ready to Merge, Tech review OK, cross-team

#772 [DOC] Mettre à jour la documentation "Faire une release"
  docs/make-a-release.mdx
Labels: :rocket: Ready to Merge

#775 [BUGFIX] fixe la navigation
  addon/components/pix-structure-switcher.js
  addon/styles/_pix-app-layout.scss
  addon/styles/_pix-navigation.scss
  addon/styles/pix-design-tokens/_spacing.scss
  tests/dummy/app/templates/application.hbs
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK
