Repository 1024pix/pix-ui, pull requests merged in 2024-03, with the labels that each got.

#556 [FEATURE] Alléger nos polices d'écriture (PIX-11485)
  addon/styles/pix-design-tokens/_fonts.scss
  public/fonts/Nunito/Nunito-Bold.ttf
  public/fonts/Nunito/nunito-latin-700-normal.woff2
  public/fonts/OpenSans/OpenSans-Medium.ttf
  public/fonts/OpenSans/open-sans-latin-700-normal.woff2
  public/fonts/Roboto/Roboto-Bold.ttf
  public/fonts/Roboto/Roboto-Medium.ttf
  public/fonts/Roboto/Roboto-Regular.ttf
  public/fonts/Roboto/roboto-latin-400-normal.woff2
  public/fonts/Roboto/roboto-latin-500-normal.woff2
  public/fonts/Roboto/roboto-latin-700-normal.woff2
Labels: :rocket: Ready to Merge, Tech review OK, cross-team

#559 [FEATURE] Migre les fonts vers woff2
  addon/styles/pix-design-tokens/_fonts.scss
  public/fonts/Nunito/Nunito-Bold.woff2
  public/fonts/Nunito/nunito-latin-700-normal.woff2
  public/fonts/OpenSans/OpenSans-Medium.woff2
  public/fonts/OpenSans/open-sans-latin-700-normal.woff2
  public/fonts/Roboto/Roboto-Bold.woff2
  public/fonts/Roboto/Roboto-Medium.woff2
  public/fonts/Roboto/Roboto-Regular.woff2
  public/fonts/Roboto/roboto-latin-400-normal.woff2
  public/fonts/Roboto/roboto-latin-500-normal.woff2
  public/fonts/Roboto/roboto-latin-700-normal.woff2
Labels: Design review OK, Func Review OK, :rocket: Ready to Merge, Tech review OK, cross-team

#550 [BUGFIX] Le `PixSearchInput` est sujet à des suppressions de caractères (PIX-11403)
  addon/components/pix-search-input.hbs
  addon/components/pix-search-input.js
  package-lock.json
  package.json
  tests/integration/components/pix-search-input-test.js
  tests/unit/components/pix-search-input-test.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, cross-team

#531 [FEATURE] Ajout de paramètres sur le composant Pix Collapsible pour afficher un tag (PIX-10851).
  addon/components/pix-collapsible.hbs
  addon/styles/_pix-collapsible.scss
  app/stories/pix-collapsible.mdx
  app/stories/pix-collapsible.stories.js
  app/stories/pix-tag.mdx
Labels: Design review OK, :rocket: Ready to Merge, cross-team

#552 [TECH] Monter Storybook en version 8
  .storybook/main.js
  .storybook/storybook-custom-theme.js
  package-lock.json
  package.json
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, cross-team

#575 [BUGFIX] Ajouter une fallback sur la pagination.
  addon/translations/index.js
  addon/translations/nl.js
Labels: :rocket: Ready to Merge

#578 [TECH] Supprimer les transition de tickets Jira via Github Actions
  .github/workflows/on-dev-merge.yml
Labels: :rocket: Ready to Merge, cross-team

#579 [TECH] Supprime la dépendance à notre fork de `@storybook-ember`
  package-lock.json
  package.json
Labels: :rocket: Ready to Merge, cross-team

#569 [TECH] Améliorer le debug des polices d'écriture (PIX-5249)
  addon/styles/pix-design-tokens/_fonts.scss
  addon/styles/pix-design-tokens/_typography.scss
  docs/typography.mdx
Labels: :rocket: Ready to Merge, Tech review OK, cross-team

#568 [BREAKING] Permettre l'usage de balise HTML dans les label des formulaire (PIX-11719)
  addon/components/pix-checkbox.hbs
  addon/components/pix-filterable-and-searchable-select.hbs
  addon/components/pix-input-base.js
  addon/components/pix-input-password.hbs
  addon/components/pix-input-password.js
  addon/components/pix-input.hbs
  addon/components/pix-input.js
  addon/components/pix-label.js
  addon/components/pix-multi-select.hbs
  addon/components/pix-multi-select.js
  addon/components/pix-pagination.hbs
  addon/components/pix-radio-button.hbs
  addon/components/pix-search-input.hbs
  addon/components/pix-search-input.js
  addon/components/pix-select.hbs
  addon/components/pix-textarea.hbs
  addon/components/pix-textarea.js
  addon/components/pix-toggle.hbs
  addon/components/pix-toggle.js
  addon/styles/_pix-input-password.scss
  addon/styles/_pix-input.scss
  addon/styles/_pix-label.scss
  addon/styles/_pix-multi-select.scss
  addon/styles/_pix-search-input.scss
  addon/styles/_pix-select.scss
  addon/styles/_pix-toggle.scss
  app/stories/form.stories.js
  app/stories/pix-checkbox.mdx
  app/stories/pix-checkbox.stories.js
  app/stories/pix-filter-banner.stories.js
  app/stories/pix-filterable-and-searchable-select.mdx
  app/stories/pix-filterable-and-searchable-select.stories.js
  app/stories/pix-input-password.mdx
  app/stories/pix-input-password.stories.js
  app/stories/pix-input.mdx
  app/stories/pix-input.stories.js
  app/stories/pix-label.stories.js
  app/stories/pix-multi-select.mdx
  app/stories/pix-multi-select.stories.js
  app/stories/pix-radio-button.mdx
  app/stories/pix-radio-button.stories.js
  app/stories/pix-search-input.mdx
  app/stories/pix-search-input.stories.js
  app/stories/pix-select.mdx
  app/stories/pix-select.stories.js
  app/stories/pix-textarea.mdx
  app/stories/pix-textarea.stories.js
  app/stories/pix-toggle.stories.js
  tests/integration/components/pix-checkbox-test.js
  tests/integration/components/pix-filterable-and-searchable-select-test.js
  tests/integration/components/pix-input-password-test.js
  tests/integration/components/pix-input-test.js
  tests/integration/components/pix-multi-select-test.js
  tests/integration/components/pix-radio-button-test.js
  tests/integration/components/pix-search-input-test.js
  tests/integration/components/pix-select-test.js
  tests/integration/components/pix-textarea-test.js
  tests/integration/components/pix-toggle-test.js
  tests/unit/components/pix-multi-select-test.js
  tests/unit/components/pix-search-input-test.js
Labels: Design review OK, Func Review OK, :rocket: Ready to Merge, Tech review OK, cross-team, :warning: BREAKING CHANGES :warning:

#583 [TECH] Déployer Storybook à chaque release
  .github/workflows/release.yml
Labels: :rocket: Ready to Merge, Tech review OK, cross-team
