Repository 1024pix/pix-ui, pull requests merged in 2025-04, with the labels that each got.

#844 [FEATURE] Ajouter la banner dans le layout du PixAppLayout (PIX-16649)
  addon/components/pix-app-layout.hbs
  addon/components/pix-app-layout.js
  addon/components/pix-navigation.js
  addon/styles/_pix-app-layout.scss
  addon/styles/_pix-navigation.scss
  app/modifiers/on-window-resize.js
  app/stories/pix-app-layout.mdx
  app/stories/pix-app-layout.stories.js
  tests/acceptance/pix-modal-page-test.js
  tests/dummy/app/router.js
  tests/dummy/app/templates/application.hbs
  tests/dummy/app/templates/layout-page.hbs
  tests/integration/components/pix-app-layout-test.js
Labels: Design review OK, Func Review OK, :rocket: Ready to Merge, Tech review OK, cross-team

#853 [BUGFIX] Ne faire apparaître le texte de PixNaviation qu'au lecteur d'écran
  addon/components/pix-navigation.hbs
  addon/components/pix-navigation.js
  app/stories/pix-navigation.stories.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, team-prescription

#802 [FEATURE] Ajouter un composant PixOverlay (PIX-15734).
  addon/components/pix-modal.hbs
  addon/components/pix-modal.js
  addon/components/pix-overlay.hbs
  addon/components/pix-overlay.js
  addon/components/pix-sidebar.hbs
  addon/components/pix-sidebar.js
  addon/styles/_pix-modal.scss
  addon/styles/_pix-overlay.scss
  addon/styles/addon.scss
  app/components/pix-overlay.js
  app/stories/pix-overlay.mdx
  app/stories/pix-overlay.stories.js
  tests/integration/components/pix-modal-test.js
  tests/integration/components/pix-overlay-test.js
  tests/integration/components/pix-sidebar-test.js
  tests/integration/modifiers/on-escape-action-test.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, cross-team

#854 [BUGFIX] Corriger l'affichage de la nav bar en mobile
  addon/styles/_pix-app-layout.scss
Labels: Func Review OK, :rocket: Ready to Merge, team-prescription, cross-team

#858 [FEATURE] Supprimer l'utilisation de withBackground dans PixIconButton (PIX-17289)
  addon/components/pix-icon-button.hbs
  addon/styles/_pix-icon-button.scss
  app/stories/pix-icon-button.mdx
  app/stories/pix-icon-button.stories.js
Labels: Design review OK, :rocket: Ready to Merge, Tech review OK

#861 [BUGFIX] Rétablir les états (hover, active) sur les éléments de menu PixLayout (PIX-17419)
  addon/components/pix-navigation-button.gjs
  addon/components/pix-navigation-button.hbs
  addon/components/pix-navigation-button.js
  addon/styles/_pix-navigation-button.scss
  tests/integration/components/pix-navigation-button-test.js
Labels: Design review OK, :rocket: Ready to Merge

#859 [TECH] Renommer la section PixBlock (PIX-16869)
  app/stories/pix-block.stories.js
Labels: :rocket: Ready to Merge, Tech review OK

#860 [FEATURE] Ajouter un attribut qui permet de supprimer les padding du PixBlock(PIX-17352)
  addon/components/pix-block.hbs
  addon/styles/_pix-block.scss
  app/stories/pix-block.stories.js
  tests/integration/components/pix-block-test.js
Labels: :rocket: Ready to Merge, Tech review OK

#857 [BUGFIX] Réparer les problèmes liés à l'overflow du PixTable
  addon/styles/_pix-table.scss
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, team-prescription

#864 [FEATURE] Ajouter icones pour keyOff(PIX-17413)
  addon/helpers/icons.js
  public/svg/pix-sprite.svg
  svgs/icons/keyOff-fill_false.svg
  svgs/icons/keyOff-fill_true.svg
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, cross-team

#866 [BUGFIX] Correction de la couleur du PixOverlay (PIX-17528)
  addon/styles/_pix-overlay.scss
Labels: Design review OK, Func Review OK, :rocket: Ready to Merge, cross-team

#863 [FEATURE] Ajout icônes arrowMenu(PIX-16993)
  addon/helpers/icons.js
  public/svg/pix-sprite.svg
  svgs/icons/arrowMenuClose-fill_false.svg
  svgs/icons/arrowMenuOpen-fill_false.svg
Labels: :rocket: Ready to Merge, Tech review OK

#862 [BUGFIX] Réparer le scroll de la modale lorsque le contenu est trop long (PIX-17422).
  addon/components/pix-modal.hbs
  addon/components/pix-overlay.hbs
  addon/styles/_pix-modal.scss
  addon/styles/_pix-overlay.scss
  app/stories/pix-overlay.stories.js
  tests/integration/modifiers/on-escape-action-test.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, cross-team
