Repository 1024pix/pix-ui, pull requests merged in 2025-01, with the labels that each got.

#798 [FEATURE] Ajouter la possibilité d'éxécuter une function lors de l'utilisation de la PixPagination (PIX-15863)
  addon/components/pix-pagination.js
  app/stories/pix-pagination.stories.js
  tests/integration/components/pix-pagination-test.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, team-prescription, cross-team

#732 [FEATURE] Montée de version vers Ember v5.11, To Infinity and Beyond (Pix-14472)
  .ember-cli
  .eslintignore
  .gitignore
  .npmignore
  .prettierignore
  blueprints/pix-component/index.js
  blueprints/pix-component/utilities/insert-into-file.js
  config/ember-try.js
  ember-cli-build.js
  package-lock.json
  package.json
  tests/dummy/app/index.html
  tests/dummy/config/ember-cli-update.json
  tests/dummy/config/environment.js
  tests/helpers/.gitkeep
  tests/integration/components/pix-checkbox-test.js
  tests/integration/components/pix-radio-button-test.js
  tests/integration/components/pix-return-to-test.js
  tests/integration/components/pix-table-column-test.js
  tests/integration/components/pix-table-test.js
  tests/unit/services/pix-toast-test.js
  vendor/.gitkeep
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, cross-team

#745 [BREAKING] :package: Mise à jour des packages autour de SASS
  addon/styles/_pix-app-layout.scss
  addon/styles/_pix-background-header.scss
  addon/styles/_pix-block.scss
  addon/styles/_pix-button-base.scss
  addon/styles/_pix-filter-banner.scss
  addon/styles/_pix-filterable-and-searchable-select.scss
  addon/styles/_pix-indicator-card.scss
  addon/styles/_pix-input-code.scss
  addon/styles/_pix-input-password.scss
  addon/styles/_pix-input.scss
  addon/styles/_pix-label.scss
  addon/styles/_pix-modal.scss
  addon/styles/_pix-multi-select.scss
  addon/styles/_pix-navigation-button.scss
  addon/styles/_pix-navigation-separator.scss
  addon/styles/_pix-navigation.scss
  addon/styles/_pix-notification-alert.scss
  addon/styles/_pix-pagination.scss
  addon/styles/_pix-progress-bar.scss
  addon/styles/_pix-return-to.scss
  addon/styles/_pix-search-input.scss
  addon/styles/_pix-select-list.scss
  addon/styles/_pix-select.scss
  addon/styles/_pix-selectable-tag.scss
  addon/styles/_pix-sidebar.scss
  addon/styles/_pix-structure-switcher.scss
  addon/styles/_pix-table.scss
  addon/styles/_pix-tag.scss
  addon/styles/_pix-textarea.scss
  addon/styles/_pix-toast.scss
  addon/styles/_pix-toggle-button.scss
  addon/styles/_pix-tooltip.scss
  addon/styles/addon.scss
  addon/styles/component-state/_form.scss
  addon/styles/component-state/index.scss
  addon/styles/normalize-reset/_reset.scss
  addon/styles/normalize-reset/index.scss
  addon/styles/pix-design-tokens/_breakpoints.scss
  addon/styles/pix-design-tokens/_typography.scss
  addon/styles/pix-design-tokens/index.scss
  package-lock.json
  package.json
Labels: :rocket: Ready to Merge, Tech review OK, cross-team, :warning: BREAKING CHANGES :warning:

#807 [FEATURE] Permettre l'affichage de pixTable en mode condensé (PIX-16082).
  addon/components/pix-table.hbs
  addon/components/pix-table.js
  addon/styles/_pix-table.scss
  app/stories/pix-table.stories.js
  tests/integration/components/pix-table-test.js
Labels: Design review OK, Func Review OK, :rocket: Ready to Merge, Tech review OK

#811 [TECH] Corriger l'exemple sur la transparence des couleurs côté documentation
  docs/colors-palette.mdx
Labels: Func Review OK, :rocket: Ready to Merge, cross-team

#809 [TECH] Mise à jour des dépendances PixUI
  package-lock.json
  package.json
Labels: Func Review OK, :rocket: Ready to Merge, cross-team

#814 [BREAKING] Supprimer les package ember-fort-awesome
  config/icons.js
  package-lock.json
  package.json
Labels: Func Review OK, :rocket: Ready to Merge, cross-team

#817 [TECH] Mise à jour des dépendences Storybook
  config/ember-try.js
  package-lock.json
  package.json
Labels: Func Review OK, :rocket: Ready to Merge, cross-team

#813 [FEATURE] Modification de l'apparence de PixFilterBanner (PIX-16053)
  addon/components/pix-filter-banner.hbs
  addon/styles/_pix-filter-banner.scss
  app/stories/pix-filter-banner.mdx
  app/stories/pix-filter-banner.stories.js
Labels: Design review OK, Func Review OK, :rocket: Ready to Merge, Tech review OK

#820 [FEATURE] Permettre à PixButtonLink d'ajouter des icônes avant et après le label (PIX-16184).
  addon/components/pix-button-link.hbs
  addon/components/pix-button-link.js
  addon/components/pix-button.hbs
  addon/components/pix-button/pix-button-content.hbs
  app/components/pix-button-content.js
  app/stories/pix-button-link.mdx
  app/stories/pix-button-link.stories.js
Labels: :rocket: Ready to Merge, cross-team

#822 [FEATURE] Modifier la liste de élements de type select pour une meilleur distinction des éléments ( PIX-16335)
  addon/components/pix-select-list.hbs
  addon/styles/_pix-select-list.scss
  addon/styles/_pix-select.scss
  addon/styles/_pix-structure-switcher.scss
  tests/dummy/app/controllers/select-page.js
  tests/integration/components/pix-select-test.js
  tests/integration/components/pix-structure-switcher-test.js
Labels: Design review OK, Func Review OK, :rocket: Ready to Merge, Tech review OK, team-prescription, cross-team
