Repository 1024pix/pix-ui, pull requests merged in 2025-03, with the labels that each got.

#834 [BUGFIX] Réparer le mode condensé de PixTable
  addon/components/pix-table.hbs
  addon/components/pix-table.js
  addon/styles/_pix-table.scss
  eslint.config.mjs
  tests/integration/components/pix-table-test.js
Labels: Func Review OK, :rocket: Ready to Merge, cross-team

#831 [FEATURE] Création d'un composant Breadcrumb (PIX-15825)
  addon/components/pix-breadcrumb.hbs
  addon/components/pix-breadcrumb.js
  addon/styles/_pix-breadcrumb.scss
  addon/styles/addon.scss
  app/components/pix-breadcrumb.js
  app/stories/pix-breadcrumb.mdx
  app/stories/pix-breadcrumb.stories.js
  tests/integration/components/pix-breadcrumb-test.js
Labels: Design review OK, Func Review OK, :rocket: Ready to Merge, Tech review OK

#838 [TECH] Autorise les lignes du tableaux à avoir une cellule de type heading scope "row" (PIX-16895)
  addon/components/pix-table-column.hbs
  addon/styles/_pix-table-column.scss
  addon/styles/_pix-table.scss
  app/stories/pix-table-column.stories.js
  tests/integration/components/pix-table-column-test.js
Labels: Func Review OK, :rocket: Ready to Merge, cross-team

#835 [FEATURE] Créer le composant PixTabs (PIX-16673).
  README.md
  addon/components/pix-tabs.hbs
  addon/components/pix-tabs.js
  addon/styles/_pix-tabs.scss
  addon/styles/addon.scss
  app/components/pix-tabs.js
  app/stories/pix-tabs.mdx
  app/stories/pix-tabs.stories.js
  docs/assets/screen-pix-storybook.png
  docs/assets/screen-pix-ui.png
  tests/integration/components/pix-tabs-test.js
Labels: Design review OK, Func Review OK, :rocket: Ready to Merge, cross-team

#833 [BREAKING] Rendre le bouton pour ouvrir la barre de navigation accessible (PIX-16754)
  addon/components/pix-navigation.hbs
  app/stories/pix-app-layout.stories.js
  app/stories/pix-navigation.mdx
  app/stories/pix-navigation.stories.js
  tests/dummy/app/templates/application.hbs
  tests/integration/components/pix-navigation-test.js
Labels: Design review OK, Func Review OK, :rocket: Ready to Merge, Tech review OK, team-evaluation

#840 [FEATURE] Mise à jour des couleurs de tags (PIX-16939)
  addon/styles/_pix-tag.scss
  app/stories/pix-tag.stories.js
Labels: Design review OK, Func Review OK, :rocket: Ready to Merge, Tech review OK, team-prescription

#839 [FEATURE] Améliorations visuelles de Pix Block (PIX-16853).
  addon/components/pix-block.hbs
  addon/components/pix-block.js
  addon/styles/_pix-block.scss
  app/stories/pix-block.mdx
  app/stories/pix-block.stories.js
  tests/integration/components/pix-background-header-test.js
  tests/integration/components/pix-block-test.js
Labels: Design review OK, Func Review OK, :rocket: Ready to Merge, Tech review OK, cross-team

#842 [FEATURE] Ajout d'un nouveau tokenfont de titre (PIX-16364)
  addon/styles/pix-design-tokens/_typography.scss
  docs/typography.mdx
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, cross-team

#841 [FEATURE] Ajout d'un variant environment pour PixBannerAlert (PIX-16912)
  addon/components/pix-banner-alert.js
  addon/styles/_pix-banner-alert.scss
  app/stories/pix-banner-alert.mdx
  app/stories/pix-banner-alert.stories.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK

#843 [FEATURE] Utiliser le PixBlock sur le PixTable (Pix-16858)
  addon/components/pix-app-layout.js
  addon/components/pix-block.js
  addon/components/pix-table.hbs
  addon/components/pix-table.js
  addon/helpers/variants.js
  addon/styles/_pix-block.scss
  addon/styles/_pix-table.scss
  app/stories/pix-app-layout.stories.js
  app/stories/pix-block.stories.js
  app/stories/pix-table.stories.js
  tests/integration/components/pix-app-layout-test.js
  tests/integration/components/pix-background-header-test.js
  tests/integration/components/pix-block-test.js
  tests/integration/components/pix-table-test.js
Labels: Design review OK, :rocket: Ready to Merge, cross-team

#845 [FEATURE] ajoute un type de colonne `checkbox` (pix-16845)
  addon/components/pix-table-column.js
  addon/styles/_pix-table-column.scss
  app/stories/pix-table-column.stories.js
  tests/dummy/app/templates/table-page.hbs
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, cross-team

#847 [FEATURE] Utiliser PixBlock pour le PixIndicatorCard (PIX-16975)
  addon/components/pix-indicator-card.hbs
  addon/styles/_pix-indicator-card.scss
Labels: Design review OK, Func Review OK, :rocket: Ready to Merge, Tech review OK, team-prescription, cross-team

#852 [FEATURE] Ajustement des marges internes des cellules de PixTable (PIX-17220)
  addon/styles/_pix-table.scss
Labels: Design review OK, :rocket: Ready to Merge, cross-team
