Repository 1024pix/pix-ui, pull requests merged in 2025-06, with the labels that each got.

#883 [FEATURE] Ajout d'un argument `isDisabled` sur PixMultiSelect
  addon/components/pix-multi-select.hbs
  app/stories/pix-multi-select.mdx
  app/stories/pix-multi-select.stories.js
  tests/integration/components/pix-multi-select-test.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK

#890 [TECH] Erreur typographique dans la story du `PixSelect`
  app/stories/pix-multi-select.stories.js
  app/stories/pix-select.mdx
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK

#884 [FEATURE] Ajouter le variant tagDate au composant PixTableColumn (PIX-16964)
  addon/components/pix-table-column.hbs
  addon/components/pix-table-column.js
  addon/styles/_pix-table-column.scss
  app/stories/pix-table-column.mdx
  app/stories/pix-table-column.stories.js
  tests/dummy/app/templates/table-page.hbs
Labels: Design review OK, Func Review OK, :rocket: Ready to Merge, Tech review OK

#885 [BUGFIX] Supprimer l'attribut disabled des PixButton (PIX-8819)
  addon/components/pix-button.hbs
  addon/components/pix-button.js
  tests/integration/components/pix-button-test.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, cross-team
