Repository 1024pix/pix-ui, pull requests merged in 2025-09, with the labels that each got.

#912 [TECH] Améliorations diverses Circle CI
  .circleci/config.yml
Labels: :rocket: Ready to Merge, Tech review OK, cross-team

#933 [FEATURE] Ajouter l'icône acute (PIX-19567)
  addon/helpers/icons.js
  public/svg/pix-sprite.svg
  svgs/icons/acute-fill_false.svg
  svgs/icons/acute-fill_true.svg
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK

#938 [TECH] Tester d'installer chrome en premier pour éviter les erreurs
  .circleci/config.yml
Labels: :rocket: Ready to Merge
