Repository 1024pix/pix-ui, pull requests merged in 2025-05, with the labels that each got.

#874 [FEATURE] Autoriser l'affichage du caption du tableau (PIX-17773)
  addon/components/pix-table.gjs
  addon/components/pix-table.hbs
  addon/styles/_pix-table.scss
  app/stories/pix-table.stories.js
Labels: Design review OK, Func Review OK, :rocket: Ready to Merge, Tech review OK, cross-team

#879 [TECH] Ajout d'une méthode dans le PixToast service pour supprimer toutes les notifications (PIX-17822)
  addon/services/pix-toast.js
  tests/unit/services/pix-toast-test.js
Labels: :rocket: Ready to Merge, Tech review OK, cross-team

#856 [TECH] Utiliser FloatingUI dans le composant PixSelect (PIX-17376).
  addon/components/pix-select-list.hbs
  addon/components/pix-select.gjs
  addon/components/pix-select.hbs
  addon/components/pix-select.js
  addon/modifiers/on-arrow-down-up-action.js
  addon/modifiers/on-enter-action.js
  addon/modifiers/on-escape-action.js
  addon/modifiers/on-space-action.js
  addon/modifiers/on-window-resize.js
  addon/modifiers/trap-focus.js
  addon/styles/_pix-select-list.scss
  addon/styles/_pix-select.scss
  app/modifiers/on-arrow-down-up-action.js
  app/modifiers/on-enter-action.js
  app/modifiers/on-escape-action.js
  app/modifiers/on-space-action.js
  app/modifiers/on-window-resize.js
  app/modifiers/trap-focus.js
  package-lock.json
  package.json
  tests/integration/components/pix-select-test.js
Labels: :rocket: Ready to Merge, Tech review OK, cross-team

#880 [FEATURE] Ajout d'un bouton permettant de lancer la requête après avoir fait un filter (PIX-17842)
  addon/components/pix-filter-banner.gjs
  addon/components/pix-filter-banner.hbs
  addon/components/pix-filter-banner.js
  addon/styles/_pix-filter-banner.scss
  app/stories/pix-filter-banner.stories.js
  tests/integration/components/pix-filter-banner-test.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, team-prescription, cross-team

#881 Revert "[TECH] Utiliser FloatingUI dans le composant PixSelect (PIX-17376)."
  addon/components/pix-select-list.hbs
  addon/components/pix-select.gjs
  addon/components/pix-select.hbs
  addon/components/pix-select.js
  addon/modifiers/on-arrow-down-up-action.js
  addon/modifiers/on-enter-action.js
  addon/modifiers/on-escape-action.js
  addon/modifiers/on-space-action.js
  addon/modifiers/on-window-resize.js
  addon/modifiers/trap-focus.js
  addon/styles/_pix-select-list.scss
  addon/styles/_pix-select.scss
  app/modifiers/on-arrow-down-up-action.js
  app/modifiers/on-enter-action.js
  app/modifiers/on-escape-action.js
  app/modifiers/on-space-action.js
  app/modifiers/on-window-resize.js
  app/modifiers/trap-focus.js
  package-lock.json
  package.json
  tests/integration/components/pix-select-test.js
Labels: :rocket: Ready to Merge, Tech review OK

#882 [BUGFIX] Corriger l'erreur d'accessibilité sur le lien externe de la PixBannerAlert (PIX-A11Y)
  addon/components/pix-banner-alert.hbs
Labels: :rocket: Ready to Merge, Tech review OK
