Repository 1024pix/pix-ui, pull requests merged in 2025-02, with the labels that each got.

#821 [FEATURE] Création du composant Pix Code (PIX-12903).
  addon/components/pix-code.hbs
  addon/components/pix-code.js
  addon/styles/_pix-code.scss
  addon/styles/addon.scss
  app/components/pix-code.js
  app/stories/pix-code.mdx
  app/stories/pix-code.stories.js
  app/stories/pix-input-code.stories.js
  tests/integration/components/pix-code-test.js
Labels: Design review OK, :rocket: Ready to Merge

#824 [FEATURE] Modifier trap-focus et la sidebar pour pouvoir désactiver le focus après fermeture de la Sidebar (PIX-16400)
  addon/components/pix-sidebar.hbs
  app/modifiers/trap-focus.js
  app/stories/pix-sidebar.stories.js
Labels: :rocket: Ready to Merge, team-devcomp

#825 [FEATURE] Ajout de nouvelles icônes (PIX-16389)
  addon/helpers/icons.js
  public/svg/pix-sprite.svg
  svgs/icons/accountOff-fill_false.svg
  svgs/icons/accountOff-fill_true.svg
  svgs/icons/play-fill_false.svg
  svgs/icons/play-fill_true.svg
Labels: Design review OK, Func Review OK, :rocket: Ready to Merge, Tech review OK, cross-team

#826 [FEATURE] Ajouter la possibilité d'utiliser une icône avant le label dans les options du pixSelect (PIX-16446)
  addon/components/pix-select-list.hbs
  addon/components/pix-select-list.js
  addon/styles/_pix-select-list.scss
  app/stories/pix-select.mdx
  app/stories/pix-select.stories.js
  tests/dummy/app/controllers/select-page.js
  tests/integration/components/pix-select-test.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, team-prescription, cross-team

#823 [FEATURE] Augmenter la taille de du pix-select afin de faire comprendre à l'utilisateur qu'il doit scroller lorsqu'il y a trop d'option (PIX-16230)
  addon/styles/_pix-select.scss
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, cross-team

#827 [FEATURE] Garder les icones dans les options du pix-select à la même taille (PIX-16568)
  addon/components/pix-select-list.hbs
  addon/styles/_pix-icon.scss
  tests/dummy/app/controllers/select-page.js
Labels: Func Review OK, :rocket: Ready to Merge, Tech review OK, team-prescription, cross-team

#829 [FEATURE] Ajout de nouvel icons sur PixUI (PIX-16680)
  addon/helpers/icons.js
  public/svg/pix-sprite.svg
  svgs/icons/mail-fill_false.svg
  svgs/icons/mail-fill_true.svg
  svgs/icons/school-fill_false.svg
  svgs/icons/school-fill_true.svg
Labels: Func Review OK, :rocket: Ready to Merge, cross-team

#828 [FEATURE] Supprimer le composant PixReturnTo 🔥 (PIX-7218).
  addon/components/pix-return-to.hbs
  addon/components/pix-return-to.js
  addon/styles/_pix-return-to.scss
  addon/styles/addon.scss
  app/components/pix-return-to.js
  app/stories/pix-return-to.mdx
  app/stories/pix-return-to.stories.js
  tests/integration/components/pix-return-to-test.js
  tests/unit/components/pix-return-to-test.js
Labels: :rocket: Ready to Merge

#830 [TECH] Ajouter un addon storybook pour afficher des tags informatifs
  .storybook/main.js
  .storybook/manager.js
  app/stories/pix-table.stories.js
  blueprints/pix-component/files/app/stories/pix-__name__.stories.js
  docs/create-component.mdx
  package-lock.json
  package.json
Labels: :rocket: Ready to Merge, cross-team
